import type { CatalogItem, Estimate, EstimateLine, Invoice, InvoiceLine, JobPhoto, Payment, ScheduleEvent } from "@/lib/types";

export const extraCatalog: CatalogItem[] = [
  { id: "cat_glaze", name: "Curtain wall / storefront", kind: "subcontract", unit: "sf", unitCost: 92, costCode: "08 44 00" },
  { id: "cat_elev", name: "Elevator package", kind: "subcontract", unit: "ea", unitCost: 285000, costCode: "14 20 00" },
  { id: "cat_fire", name: "Fire sprinkler", kind: "subcontract", unit: "sf", unitCost: 4.1, costCode: "21 13 00" },
  { id: "cat_icra", name: "ICRA containment", kind: "labor", unit: "ls", unitCost: 18500, costCode: "01 35 00" },
  { id: "cat_mill", name: "Architectural millwork", kind: "subcontract", unit: "lf", unitCost: 420, costCode: "06 41 00" },
  { id: "cat_floor", name: "LVT / carpet tile", kind: "material", unit: "sf", unitCost: 6.8, costCode: "09 65 00" },
  { id: "cat_site", name: "Site utilities", kind: "subcontract", unit: "LS", unitCost: 840000, costCode: "33 00 00" },
  { id: "cat_night", name: "Night-work premium", kind: "allowance", unit: "mo", unitCost: 18000, costCode: "01 11 00" },
];

export const extraEstimates: Estimate[] = [
  {
    id: "est_or4",
    number: "EST-1005",
    name: "Children's OR Suite 4 — GMP",
    clientId: "cli_childrens",
    opportunityId: "opp_or4",
    jobId: null,
    status: "sent",
    notes: "GMP at 80% CDs. ICRA and after-hours in general conditions. MRI not in this package.",
    validUntil: "2026-09-09",
    sentAt: "2026-08-19T20:15:00.000Z",
    acceptedAt: null,
    createdAt: "2026-08-08T15:00:00.000Z",
  },
  {
    id: "est_oxford",
    number: "EST-1006",
    name: "Oxford Hotel Guestroom Refresh",
    clientId: "cli_sage",
    opportunityId: "opp_oxford",
    jobId: null,
    status: "sent",
    notes: "12 rooms/week, hotel open. FF&E owner-furnished. Night premium included.",
    validUntil: "2026-09-03",
    sentAt: "2026-08-17T19:00:00.000Z",
    acceptedAt: null,
    createdAt: "2026-08-10T16:40:00.000Z",
  },
  {
    id: "est_pearl",
    number: "EST-1007",
    name: "Pearl Street Mixed-Use — working",
    clientId: "cli_redstone",
    opportunityId: "opp_pearl",
    jobId: null,
    status: "draft",
    notes: "Hold energy-code HVAC until Cleo picks a path. Do not send.",
    validUntil: "2026-09-30",
    sentAt: null,
    acceptedAt: null,
    createdAt: "2026-08-15T14:00:00.000Z",
  },
  {
    id: "est_roast",
    number: "EST-1008",
    name: "Flatiron Roastery GMP",
    clientId: "cli_flatiron",
    opportunityId: "opp_roast",
    jobId: "job_flatiron",
    status: "accepted",
    notes: "Accepted pending bank. Job is on hold until FirstBank funds.",
    validUntil: "2026-09-15",
    sentAt: "2026-08-14T18:00:00.000Z",
    acceptedAt: "2026-08-18T16:20:00.000Z",
    createdAt: "2026-08-06T15:30:00.000Z",
  },
  {
    id: "est_lohi",
    number: "EST-1009",
    name: "LoHi Commons Phase 2 — schematic",
    clientId: "cli_larimer",
    opportunityId: "opp_lohi",
    jobId: null,
    status: "viewed",
    notes: "Joy opened the file Tuesday. Staffing chart still outstanding.",
    validUntil: "2026-09-18",
    sentAt: "2026-08-16T17:00:00.000Z",
    acceptedAt: null,
    createdAt: "2026-08-09T19:00:00.000Z",
  },
  {
    id: "est_uc_lab",
    number: "EST-1010",
    name: "UCHealth Central Lab — design-assist",
    clientId: "cli_uchealth",
    opportunityId: "opp_uc_lab",
    jobId: null,
    status: "draft",
    notes: "Vibration criteria still open. Do not send a number.",
    validUntil: "2026-10-01",
    sentAt: null,
    acceptedAt: null,
    createdAt: "2026-08-18T14:10:00.000Z",
  },
];

export const extraEstimateLines: EstimateLine[] = [
  { id: "el_or_1", estimateId: "est_or4", catalogItemId: "cat_demo", description: "Selective demolition — occupied OR floor", quantity: 6400, unit: "sf", unitCost: 6.4, sortOrder: 0 },
  { id: "el_or_2", estimateId: "est_or4", catalogItemId: "cat_icra", description: "ICRA containment & monitoring", quantity: 4, unit: "ls", unitCost: 18500, sortOrder: 1 },
  { id: "el_or_3", estimateId: "est_or4", catalogItemId: "cat_mep_pkg", description: "MEP for four ORs", quantity: 1, unit: "LS", unitCost: 4120000, sortOrder: 2 },
  { id: "el_or_4", estimateId: "est_or4", catalogItemId: "cat_int", description: "Surgical interiors & casework", quantity: 1, unit: "LS", unitCost: 1860000, sortOrder: 3 },
  { id: "el_or_5", estimateId: "est_or4", catalogItemId: "cat_gc", description: "General conditions — after hours", quantity: 1, unit: "LS", unitCost: 920000, sortOrder: 4 },
  { id: "el_ox_1", estimateId: "est_oxford", catalogItemId: "cat_demo", description: "Guestroom selective demo", quantity: 18000, unit: "sf", unitCost: 6.4, sortOrder: 0 },
  { id: "el_ox_2", estimateId: "est_oxford", catalogItemId: "cat_mill", description: "Headboard millwork", quantity: 240, unit: "lf", unitCost: 420, sortOrder: 1 },
  { id: "el_ox_3", estimateId: "est_oxford", catalogItemId: "cat_floor", description: "Guestroom flooring", quantity: 18000, unit: "sf", unitCost: 6.8, sortOrder: 2 },
  { id: "el_ox_4", estimateId: "est_oxford", catalogItemId: "cat_night", description: "Night-work premium", quantity: 5, unit: "mo", unitCost: 18000, sortOrder: 3 },
  { id: "el_ox_5", estimateId: "est_oxford", catalogItemId: "cat_paint", description: "Interior paint", quantity: 36000, unit: "sf", unitCost: 1.95, sortOrder: 4 },
  { id: "el_pe_1", estimateId: "est_pearl", catalogItemId: "cat_conc_pkg", description: "Podium concrete", quantity: 1, unit: "LS", unitCost: 6400000, sortOrder: 0 },
  { id: "el_pe_2", estimateId: "est_pearl", catalogItemId: "cat_carp", description: "Type V framing", quantity: 42000, unit: "lf", unitCost: 12.4, sortOrder: 1 },
  { id: "el_pe_3", estimateId: "est_pearl", catalogItemId: "cat_glaze", description: "Storefront at Pearl", quantity: 8200, unit: "sf", unitCost: 92, sortOrder: 2 },
  { id: "el_pe_4", estimateId: "est_pearl", catalogItemId: "cat_elev", description: "Elevators", quantity: 3, unit: "ea", unitCost: 285000, sortOrder: 3 },
  { id: "el_ro_1", estimateId: "est_roast", catalogItemId: "cat_conc_pkg", description: "Roaster pad & SOG", quantity: 1, unit: "LS", unitCost: 420000, sortOrder: 0 },
  { id: "el_ro_2", estimateId: "est_roast", catalogItemId: "cat_mep_pkg", description: "Process MEP & grease exhaust", quantity: 1, unit: "LS", unitCost: 1280000, sortOrder: 1 },
  { id: "el_ro_3", estimateId: "est_roast", catalogItemId: "cat_int", description: "Tasting room interiors", quantity: 1, unit: "LS", unitCost: 640000, sortOrder: 2 },
  { id: "el_lo_1", estimateId: "est_lohi", catalogItemId: "cat_steel", description: "Podium steel", quantity: 1, unit: "LS", unitCost: 4100000, sortOrder: 0 },
  { id: "el_lo_2", estimateId: "est_lohi", catalogItemId: "cat_carp", description: "Wood-frame apartments", quantity: 28000, unit: "lf", unitCost: 12.4, sortOrder: 1 },
  { id: "el_lo_3", estimateId: "est_lohi", catalogItemId: "cat_hvac", description: "HVAC", quantity: 210000, unit: "sf", unitCost: 18.2, sortOrder: 2 },
  { id: "el_uc_1", estimateId: "est_uc_lab", catalogItemId: "cat_mep_pkg", description: "Lab MEP design-assist", quantity: 1, unit: "LS", unitCost: 5400000, sortOrder: 0 },
  { id: "el_uc_2", estimateId: "est_uc_lab", catalogItemId: "cat_int", description: "Lab casework & finishes", quantity: 1, unit: "LS", unitCost: 2100000, sortOrder: 1 },
];

export const extraInvoices: Invoice[] = [
  {
    id: "inv_oxford_2",
    number: "INV-2005",
    name: "Crawford Hotel — Application 2",
    clientId: "cli_sage",
    jobId: "job_oxford",
    estimateId: null,
    status: "sent",
    issuedAt: "2026-08-05",
    dueAt: "2026-08-20",
    notes: "Corridors floors 2–3. Millwork delay noted; no claim yet.",
  },
  {
    id: "inv_confluence",
    number: "INV-2006",
    name: "Confluence amenities — Application 3",
    clientId: "cli_larimer",
    jobId: "job_larimer_am",
    estimateId: null,
    status: "partial",
    issuedAt: "2026-08-01",
    dueAt: "2026-08-31",
    notes: "Pool plaster next. Draw certified by Joy.",
  },
  {
    id: "inv_jeffco",
    number: "INV-2007",
    name: "Jeffco Fleet Shop — final & retainage",
    clientId: "cli_jeffco",
    jobId: "job_jeffco_yard",
    estimateId: null,
    status: "overdue",
    issuedAt: "2026-07-28",
    dueAt: "2026-08-12",
    notes: "Waiting on county AP. Punch is 22 items.",
  },
  {
    id: "inv_osage",
    number: "INV-2008",
    name: "Osage envelope — final",
    clientId: "cli_dha",
    jobId: "job_dha_osage",
    estimateId: null,
    status: "paid",
    issuedAt: "2026-04-04",
    dueAt: "2026-05-04",
    notes: "Paid in full after warranty walk.",
  },
  {
    id: "inv_suite200",
    number: "INV-2009",
    name: "Copperline Suite 200 — retainage",
    clientId: "cli_copperline",
    jobId: "job_copper_200",
    estimateId: null,
    status: "paid",
    issuedAt: "2026-05-02",
    dueAt: "2026-05-16",
    notes: "Helen released retainage after the one-year walk.",
  },
  {
    id: "inv_school_6",
    number: "INV-2010",
    name: "DPS West High CTE — Application 6",
    clientId: "cli_dps",
    jobId: "job_school",
    estimateId: null,
    status: "sent",
    issuedAt: "2026-08-10",
    dueAt: "2026-09-09",
    notes: "Overheads after-hours. Prevailing wage certified payroll attached.",
  },
];

export const extraInvoiceLines: InvoiceLine[] = [
  { id: "il_7", invoiceId: "inv_oxford_2", description: "Corridor demo & framing — floors 2–3", quantity: 1, unit: "LS", unitCost: 186000, sortOrder: 0 },
  { id: "il_8", invoiceId: "inv_oxford_2", description: "Night-work premium — July", quantity: 1, unit: "mo", unitCost: 18000, sortOrder: 1 },
  { id: "il_9", invoiceId: "inv_confluence", description: "Amenity interiors — 70%", quantity: 0.7, unit: "LS", unitCost: 1240000, sortOrder: 0 },
  { id: "il_10", invoiceId: "inv_confluence", description: "Pool mechanical — 40%", quantity: 0.4, unit: "LS", unitCost: 380000, sortOrder: 1 },
  { id: "il_11", invoiceId: "inv_jeffco", description: "Contract remainder + retainage", quantity: 1, unit: "LS", unitCost: 335000, sortOrder: 0 },
  { id: "il_12", invoiceId: "inv_osage", description: "Final envelope & closeout", quantity: 1, unit: "LS", unitCost: 195000, sortOrder: 0 },
  { id: "il_13", invoiceId: "inv_suite200", description: "Retainage 5%", quantity: 1, unit: "LS", unitCost: 82500, sortOrder: 0 },
  { id: "il_14", invoiceId: "inv_school_6", description: "Shop overheads — July", quantity: 1, unit: "LS", unitCost: 412000, sortOrder: 0 },
];

export const extraPayments: Payment[] = [
  {
    id: "pay_3",
    invoiceId: "inv_confluence",
    amount: 520000,
    method: "ACH",
    paidAt: "2026-08-18",
    reference: "Larimer draw 3 — partial",
  },
  {
    id: "pay_4",
    invoiceId: "inv_osage",
    amount: 195000,
    method: "ACH",
    paidAt: "2026-05-02",
    reference: "DHA closeout",
  },
  {
    id: "pay_5",
    invoiceId: "inv_suite200",
    amount: 82500,
    method: "check",
    paidAt: "2026-05-12",
    reference: "Copperline retainage",
  },
];

export const extraEvents: ScheduleEvent[] = [
  {
    id: "evt_11",
    title: "OR 4 ICRA walk with Mira",
    kind: "site_walk",
    startsAt: "2026-08-21T15:00:00.000Z",
    endsAt: "2026-08-21T16:30:00.000Z",
    location: "Anschutz campus",
    assignee: "Maya Chen",
    opportunityId: "opp_or4",
    jobId: null,
    clientId: "cli_childrens",
    notes: "After-hours. Badge required.",
  },
  {
    id: "evt_12",
    title: "Crawford night shift kickoff",
    kind: "production",
    startsAt: "2026-08-20T03:00:00.000Z",
    endsAt: "2026-08-20T11:00:00.000Z",
    location: "Crawford Hotel",
    assignee: "Tom Brennan",
    opportunityId: null,
    jobId: "job_oxford",
    clientId: "cli_sage",
    notes: "Floors 2–3. Quiet hours until 7 a.m.",
  },
  {
    id: "evt_13",
    title: "Jeffco punch with fleet",
    kind: "punch",
    startsAt: "2026-08-24T15:00:00.000Z",
    endsAt: "2026-08-24T17:00:00.000Z",
    location: "Golden shop",
    assignee: "Luis Ortega",
    opportunityId: null,
    jobId: "job_jeffco_yard",
    clientId: "cli_jeffco",
    notes: "Wash bay epoxy is the remaining item.",
  },
  {
    id: "evt_14",
    title: "LoHi Commons interview",
    kind: "meeting",
    startsAt: "2026-08-25T16:00:00.000Z",
    endsAt: "2026-08-25T17:30:00.000Z",
    location: "Larimer office",
    assignee: "Elena Voss",
    opportunityId: "opp_lohi",
    jobId: null,
    clientId: "cli_larimer",
    notes: "Bring staffing chart and occupied-rehab references.",
  },
  {
    id: "evt_15",
    title: "Pearl Street pre-bid walk",
    kind: "pre_bid",
    startsAt: "2026-08-28T15:00:00.000Z",
    endsAt: "2026-08-28T17:00:00.000Z",
    location: "Pearl Street, Boulder",
    assignee: "Priya Shah",
    opportunityId: "opp_pearl",
    jobId: null,
    clientId: "cli_redstone",
    notes: "Mandatory. Bring energy-code questions.",
  },
  {
    id: "evt_16",
    title: "Confluence pool plaster",
    kind: "production",
    startsAt: "2026-08-26T14:00:00.000Z",
    endsAt: "2026-08-26T22:00:00.000Z",
    location: "The Confluence",
    assignee: "Tom Brennan",
    opportunityId: null,
    jobId: "job_larimer_am",
    clientId: "cli_larimer",
    notes: "Occupied building. Isolation at amenity level.",
  },
  {
    id: "evt_17",
    title: "UCHealth lab vibration meeting",
    kind: "meeting",
    startsAt: "2026-09-03T17:00:00.000Z",
    endsAt: "2026-09-03T18:00:00.000Z",
    location: "Teams",
    assignee: "Maya Chen",
    opportunityId: "opp_uc_lab",
    jobId: null,
    clientId: "cli_uchealth",
    notes: "Analyzer vendor on the call.",
  },
  {
    id: "evt_18",
    title: "Infusion center precon kickoff",
    kind: "meeting",
    startsAt: "2026-08-27T15:00:00.000Z",
    endsAt: "2026-08-27T16:30:00.000Z",
    location: "Anschutz",
    assignee: "Elena Voss",
    opportunityId: null,
    jobId: "job_child_infill",
    clientId: "cli_childrens",
    notes: "Greg and Mira. Start Oct 12.",
  },
];

export const extraPhotos: JobPhoto[] = [
  {
    id: "ph_8",
    jobId: "job_oxford",
    caption: "Crawford corridor before night shift — floors 2–3.",
    category: "before",
    takenAt: "2026-08-12",
    imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1400&q=80",
    storagePath: null,
  },
  {
    id: "ph_9",
    jobId: "job_oxford",
    caption: "New millwork at the elevator lobby. Waiting on brand hardware.",
    category: "progress",
    takenAt: "2026-08-17",
    imageUrl: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=1400&q=80",
    storagePath: null,
  },
  {
    id: "ph_10",
    jobId: "job_larimer_am",
    caption: "Amenity level isolation before pool plaster.",
    category: "progress",
    takenAt: "2026-08-13",
    imageUrl: "https://images.unsplash.com/photo-1576013551627-0cc20b96c2f7?auto=format&fit=crop&w=1400&q=80",
    storagePath: null,
  },
  {
    id: "ph_11",
    jobId: "job_jeffco_yard",
    caption: "Fleet shop wash bay — epoxy is the last punch item.",
    category: "issue",
    takenAt: "2026-08-15",
    imageUrl: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=1400&q=80",
    storagePath: null,
  },
  {
    id: "ph_12",
    jobId: "job_dha_osage",
    caption: "Osage envelope complete — south elevation.",
    category: "after",
    takenAt: "2026-03-20",
    imageUrl: "https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=1400&q=80",
    storagePath: null,
  },
  {
    id: "ph_13",
    jobId: "job_copper_200",
    caption: "Suite 200 after punch — ready for tenant.",
    category: "after",
    takenAt: "2026-04-10",
    imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1400&q=80",
    storagePath: null,
  },
  {
    id: "ph_14",
    jobId: "job_rec",
    caption: "Aurora Rec Center existing natatorium — precon photo.",
    category: "before",
    takenAt: "2026-08-08",
    imageUrl: "https://images.unsplash.com/photo-1576013551627-0cc20b96c2f7?auto=format&fit=crop&w=1400&q=80",
    storagePath: null,
  },
];
