import type { CatalogItem, Invoice, InvoiceLine, JobPhoto, Payment, ScheduleEvent } from "@/lib/types";
import type { EstimateDraft, EstimateLineDraft } from "@/lib/estimate-totals";

export const extraCatalog: CatalogItem[] = [
  { id: "cat_tear", name: "Roof tear-off", kind: "labor", unit: "sq", unitCost: 185, costCode: "07 31 00" },
  { id: "cat_shingle", name: "Architectural shingles", kind: "material", unit: "sq", unitCost: 420, costCode: "07 31 13" },
  { id: "cat_gutter", name: "Gutters & downspouts", kind: "subcontract", unit: "lf", unitCost: 12.5, costCode: "07 71 00" },
  { id: "cat_extract", name: "Water extraction", kind: "labor", unit: "ls", unitCost: 2400, costCode: "02 41 19" },
  { id: "cat_dry", name: "Drying equipment", kind: "equipment", unit: "day", unitCost: 185, costCode: "01 54 00" },
  { id: "cat_cab", name: "Kitchen cabinets", kind: "material", unit: "lf", unitCost: 480, costCode: "06 41 00" },
  { id: "cat_quartz", name: "Quartz countertops", kind: "subcontract", unit: "sf", unitCost: 72, costCode: "12 36 00" },
  { id: "cat_tile", name: "Tile floors & wet walls", kind: "labor", unit: "sf", unitCost: 18.5, costCode: "09 30 00" },
  { id: "cat_siding", name: "Fiber-cement siding", kind: "subcontract", unit: "sf", unitCost: 9.4, costCode: "07 46 00" },
  { id: "cat_window", name: "Vinyl window unit", kind: "material", unit: "ea", unitCost: 780, costCode: "08 53 00" },
  { id: "cat_dump", name: "Dumpster", kind: "allowance", unit: "ea", unitCost: 650, costCode: "02 41 00" },
  { id: "cat_packout", name: "Contents pack-out", kind: "allowance", unit: "ls", unitCost: 4800, costCode: "02 41 19" },
];

export const extraEstimates: EstimateDraft[] = [
  {
    id: "est_ellison",
    number: "EST-1001",
    name: "Ellison kitchen — Wash Park",
    clientId: null,
    opportunityId: "opp_ellison_kit",
    jobId: null,
    status: "draft",
    notes: "Hold the island until the engineer letter lands. Brook wants it listed in October.",
    validUntil: "2026-09-10",
    sentAt: null,
    acceptedAt: null,
    createdAt: "2026-08-16T15:00:00.000Z",
  },
  {
    id: "est_marsh",
    number: "EST-1002",
    name: "Marsh primary bath — LoHi",
    clientId: null,
    opportunityId: "opp_marsh_bath",
    jobId: null,
    status: "sent",
    notes: "Tile allowance $14/sf. Friday start if he signs this week.",
    validUntil: "2026-09-04",
    sentAt: "2026-08-17T19:10:00.000Z",
    acceptedAt: null,
    createdAt: "2026-08-14T16:20:00.000Z",
  },
  {
    id: "est_hart_kit",
    number: "EST-1003",
    name: "Hart kitchen rebuild after water",
    clientId: null,
    opportunityId: "opp_hart_rebuild",
    jobId: "job_hart_water",
    status: "draft",
    notes: "Waiting on Nina’s contents list. Do not send a number yet.",
    validUntil: "2026-09-08",
    sentAt: null,
    acceptedAt: null,
    createdAt: "2026-08-18T15:40:00.000Z",
  },
  {
    id: "est_whitfield_kit",
    number: "EST-1004",
    name: "Whitfield kitchen after basement",
    clientId: null,
    opportunityId: "opp_whitfield_kit",
    jobId: "job_whitfield_bsmt",
    status: "sent",
    notes: "Start the day the basement punches. Same crew.",
    validUntil: "2026-09-07",
    sentAt: "2026-08-16T18:00:00.000Z",
    acceptedAt: null,
    createdAt: "2026-08-12T17:00:00.000Z",
  },
  {
    id: "est_pell",
    number: "EST-1005",
    name: "Pell roof + gutters — Lakewood",
    clientId: null,
    opportunityId: "opp_pell_roof",
    jobId: null,
    status: "viewed",
    notes: "Al opened it Tuesday. Skylight supplement still outstanding.",
    validUntil: "2026-09-08",
    sentAt: "2026-08-18T16:00:00.000Z",
    acceptedAt: null,
    createdAt: "2026-08-14T14:10:00.000Z",
  },
  {
    id: "est_park",
    number: "EST-1006",
    name: "Park kitchen — Hilltop",
    clientId: null,
    opportunityId: "opp_park_kitchen",
    jobId: null,
    status: "sent",
    notes: "Joy wants references, not a brochure. Photos attached.",
    validUntil: "2026-09-11",
    sentAt: "2026-08-19T17:20:00.000Z",
    acceptedAt: null,
    createdAt: "2026-08-15T18:00:00.000Z",
  },
  {
    id: "est_alvarez",
    number: "EST-1007",
    name: "Alvarez hail roof — sold",
    clientId: null,
    opportunityId: "opp_alvarez_roof",
    jobId: "job_alvarez_roof",
    status: "accepted",
    notes: "Insurance ACV plus supplement. Production is on the roof.",
    validUntil: null,
    sentAt: "2026-07-16T18:00:00.000Z",
    acceptedAt: "2026-07-22T15:10:00.000Z",
    createdAt: "2026-07-12T16:00:00.000Z",
  },
  {
    id: "est_blake",
    number: "EST-1008",
    name: "Blake kitchen — sold",
    clientId: null,
    opportunityId: "opp_blake_kitchen",
    jobId: "job_blake_kitchen",
    status: "accepted",
    notes: "Fixed price. Cabinets owner-selected, we install.",
    validUntil: null,
    sentAt: "2026-06-04T17:00:00.000Z",
    acceptedAt: "2026-06-10T16:20:00.000Z",
    createdAt: "2026-05-28T15:30:00.000Z",
  },
  {
    id: "est_calder_win",
    number: "EST-1009",
    name: "Calder west windows — working",
    clientId: null,
    opportunityId: "opp_calder_win",
    jobId: "job_calder_siding",
    status: "draft",
    notes: "Four units while the siding crew is still on site. Do not send until Ivy confirms color.",
    validUntil: "2026-09-15",
    sentAt: null,
    acceptedAt: null,
    createdAt: "2026-08-17T16:40:00.000Z",
  },
  {
    id: "est_redmond",
    number: "EST-1010",
    name: "Redmond rear addition — GMP",
    clientId: null,
    opportunityId: "opp_redmond_add",
    jobId: "job_redmond_add",
    status: "accepted",
    notes: "Permit set with Hale + Moss. Start after Labor Day.",
    validUntil: null,
    sentAt: "2026-08-10T18:00:00.000Z",
    acceptedAt: "2026-08-18T16:00:00.000Z",
    createdAt: "2026-08-02T15:00:00.000Z",
  },
];

export const extraEstimateLines: EstimateLineDraft[] = [
  { id: "el_e1", estimateId: "est_ellison", catalogItemId: "cat_demo", description: "Kitchen demo", quantity: 280, unit: "sf", unitCost: 6.4, sortOrder: 0 },
  { id: "el_e2", estimateId: "est_ellison", catalogItemId: "cat_cab", description: "Cabinets", quantity: 28, unit: "lf", unitCost: 480, sortOrder: 1 },
  { id: "el_e3", estimateId: "est_ellison", catalogItemId: "cat_quartz", description: "Quartz — island and walls", quantity: 62, unit: "sf", unitCost: 72, sortOrder: 2 },
  { id: "el_e4", estimateId: "est_ellison", catalogItemId: "cat_elec", description: "Electrical rough & trim", quantity: 280, unit: "sf", unitCost: 14.5, sortOrder: 3 },
  { id: "el_m1", estimateId: "est_marsh", catalogItemId: "cat_demo", description: "Bath demo", quantity: 48, unit: "sf", unitCost: 6.4, sortOrder: 0 },
  { id: "el_m2", estimateId: "est_marsh", catalogItemId: "cat_tile", description: "Tile floors & wet walls", quantity: 120, unit: "sf", unitCost: 18.5, sortOrder: 1 },
  { id: "el_m3", estimateId: "est_marsh", catalogItemId: "cat_plumb", description: "Plumbing rough", quantity: 48, unit: "sf", unitCost: 9.8, sortOrder: 2 },
  { id: "el_h1", estimateId: "est_hart_kit", catalogItemId: "cat_cab", description: "Replacement cabinets", quantity: 18, unit: "lf", unitCost: 480, sortOrder: 0 },
  { id: "el_h2", estimateId: "est_hart_kit", catalogItemId: "cat_dw", description: "Drywall after dry-out", quantity: 420, unit: "sf", unitCost: 3.65, sortOrder: 1 },
  { id: "el_w1", estimateId: "est_whitfield_kit", catalogItemId: "cat_cab", description: "Kitchen cabinets", quantity: 24, unit: "lf", unitCost: 480, sortOrder: 0 },
  { id: "el_w2", estimateId: "est_whitfield_kit", catalogItemId: "cat_quartz", description: "Quartz tops", quantity: 48, unit: "sf", unitCost: 72, sortOrder: 1 },
  { id: "el_p1", estimateId: "est_pell", catalogItemId: "cat_tear", description: "Tear-off", quantity: 28, unit: "sq", unitCost: 185, sortOrder: 0 },
  { id: "el_p2", estimateId: "est_pell", catalogItemId: "cat_shingle", description: "Architectural shingles", quantity: 28, unit: "sq", unitCost: 420, sortOrder: 1 },
  { id: "el_p3", estimateId: "est_pell", catalogItemId: "cat_gutter", description: "Gutters", quantity: 140, unit: "lf", unitCost: 12.5, sortOrder: 2 },
  { id: "el_p4", estimateId: "est_pell", catalogItemId: "cat_gutter", description: "Leaf guards", quantity: 140, unit: "lf", unitCost: 8, sortOrder: 3 },
  { id: "el_pk1", estimateId: "est_park", catalogItemId: "cat_cab", description: "Cabinets", quantity: 32, unit: "lf", unitCost: 480, sortOrder: 0 },
  { id: "el_pk2", estimateId: "est_park", catalogItemId: "cat_quartz", description: "Quartz", quantity: 70, unit: "sf", unitCost: 72, sortOrder: 1 },
  { id: "el_a1", estimateId: "est_alvarez", catalogItemId: "cat_tear", description: "Tear-off", quantity: 32, unit: "sq", unitCost: 185, sortOrder: 0 },
  { id: "el_a2", estimateId: "est_alvarez", catalogItemId: "cat_shingle", description: "Shingles", quantity: 32, unit: "sq", unitCost: 420, sortOrder: 1 },
  { id: "el_a3", estimateId: "est_alvarez", catalogItemId: "cat_dump", description: "Dumpster", quantity: 1, unit: "ea", unitCost: 650, sortOrder: 2 },
  { id: "el_b1", estimateId: "est_blake", catalogItemId: "cat_cab", description: "Cabinets install", quantity: 22, unit: "lf", unitCost: 480, sortOrder: 0 },
  { id: "el_b2", estimateId: "est_blake", catalogItemId: "cat_quartz", description: "Quartz", quantity: 44, unit: "sf", unitCost: 72, sortOrder: 1 },
  { id: "el_c1", estimateId: "est_calder_win", catalogItemId: "cat_window", description: "West elevation windows", quantity: 4, unit: "ea", unitCost: 780, sortOrder: 0 },
  { id: "el_r1", estimateId: "est_redmond", catalogItemId: "cat_carp", description: "Addition framing", quantity: 420, unit: "lf", unitCost: 12.4, sortOrder: 0 },
  { id: "el_r2", estimateId: "est_redmond", catalogItemId: "cat_conc_pkg", description: "Footings", quantity: 1, unit: "LS", unitCost: 18400, sortOrder: 1 },
  { id: "el_r3", estimateId: "est_redmond", catalogItemId: "cat_dw", description: "Drywall", quantity: 2400, unit: "sf", unitCost: 3.65, sortOrder: 2 },
];

export const extraInvoices: Omit<Invoice, "shareToken">[] = [
  {
    id: "inv_alvarez_1",
    number: "INV-2001",
    name: "Alvarez roof — progress",
    clientId: null,
    jobId: "job_alvarez_roof",
    estimateId: "est_alvarez",
    status: "sent",
    issuedAt: "2026-08-12",
    dueAt: "2026-08-26",
    notes: "Tear-off and felt. Final when shingles complete.",
  },
  {
    id: "inv_hart_dry",
    number: "INV-2002",
    name: "Hart dry-out — emergency",
    clientId: null,
    jobId: "job_hart_water",
    estimateId: null,
    status: "partial",
    issuedAt: "2026-07-18",
    dueAt: "2026-08-01",
    notes: "Carrier paid extraction. Rebuild is a second invoice.",
  },
  {
    id: "inv_blake_2",
    number: "INV-2003",
    name: "Blake kitchen — Application 2",
    clientId: null,
    jobId: "job_blake_kitchen",
    estimateId: "est_blake",
    status: "sent",
    issuedAt: "2026-08-08",
    dueAt: "2026-08-22",
    notes: "Demo and rough-in. Cabinets next.",
  },
  {
    id: "inv_whitfield_3",
    number: "INV-2004",
    name: "Whitfield basement — Application 3",
    clientId: null,
    jobId: "job_whitfield_bsmt",
    estimateId: null,
    status: "partial",
    issuedAt: "2026-08-01",
    dueAt: "2026-08-15",
    notes: "Framing and insulation. Mechanical next.",
  },
  {
    id: "inv_calder_final",
    number: "INV-2005",
    name: "Calder siding — retainage",
    clientId: null,
    jobId: "job_calder_siding",
    estimateId: null,
    status: "overdue",
    issuedAt: "2026-08-04",
    dueAt: "2026-08-18",
    notes: "Punch two wraps, then she releases retainage.",
  },
  {
    id: "inv_patel",
    number: "INV-2006",
    name: "Patel roof — final",
    clientId: null,
    jobId: "job_patel_roof",
    estimateId: null,
    status: "paid",
    issuedAt: "2026-04-06",
    dueAt: "2026-04-20",
    notes: "Paid in full after warranty walk.",
  },
  {
    id: "inv_nguyen",
    number: "INV-2007",
    name: "Nguyen windows — final",
    clientId: null,
    jobId: "job_nguyen_windows",
    estimateId: null,
    status: "paid",
    issuedAt: "2026-03-30",
    dueAt: "2026-04-13",
    notes: "Cara mailed a check the week after punch.",
  },
  {
    id: "inv_nash",
    number: "INV-2008",
    name: "Nash deck — final",
    clientId: null,
    jobId: "job_nash_deck",
    estimateId: null,
    status: "paid",
    issuedAt: "2026-05-18",
    dueAt: "2026-06-01",
    notes: "Paid. Stain warranty in closeout.",
  },
  {
    id: "inv_copper",
    number: "INV-2009",
    name: "Copperline Suite 200 — retainage",
    clientId: "cli_copperline",
    jobId: "job_copper_200",
    estimateId: null,
    status: "paid",
    issuedAt: "2026-05-02",
    dueAt: "2026-05-16",
    notes: "Helen released retainage after the one-year walk.",
  },
  {
    id: "inv_redmond_dep",
    number: "INV-2010",
    name: "Redmond addition — deposit",
    clientId: null,
    jobId: "job_redmond_add",
    estimateId: "est_redmond",
    status: "sent",
    issuedAt: "2026-08-19",
    dueAt: "2026-09-02",
    notes: "10% deposit against the accepted GMP. Permit not yet issued.",
  },
];

export const extraInvoiceLines: InvoiceLine[] = [
  { id: "il_r1", invoiceId: "inv_alvarez_1", description: "Tear-off and underlayment", quantity: 1, unit: "LS", unitCost: 12400, sortOrder: 0 },
  { id: "il_r2", invoiceId: "inv_hart_dry", description: "Water extraction", quantity: 1, unit: "ls", unitCost: 2400, sortOrder: 0 },
  { id: "il_r3", invoiceId: "inv_hart_dry", description: "Drying equipment — 9 days", quantity: 9, unit: "day", unitCost: 185, sortOrder: 1 },
  { id: "il_r4", invoiceId: "inv_blake_2", description: "Demo and mechanical rough", quantity: 1, unit: "LS", unitCost: 18600, sortOrder: 0 },
  { id: "il_r5", invoiceId: "inv_whitfield_3", description: "Framing and insulation — 70%", quantity: 0.7, unit: "LS", unitCost: 28000, sortOrder: 0 },
  { id: "il_r6", invoiceId: "inv_calder_final", description: "Retainage 10%", quantity: 1, unit: "LS", unitCost: 3180, sortOrder: 0 },
  { id: "il_r7", invoiceId: "inv_patel", description: "Roof replacement — final", quantity: 1, unit: "LS", unitCost: 19200, sortOrder: 0 },
  { id: "il_r8", invoiceId: "inv_nguyen", description: "Window package — final", quantity: 1, unit: "LS", unitCost: 22100, sortOrder: 0 },
  { id: "il_r9", invoiceId: "inv_nash", description: "Deck rebuild — final", quantity: 1, unit: "LS", unitCost: 24600, sortOrder: 0 },
  { id: "il_r10", invoiceId: "inv_copper", description: "Retainage 5%", quantity: 1, unit: "LS", unitCost: 9300, sortOrder: 0 },
  { id: "il_r11", invoiceId: "inv_redmond_dep", description: "Deposit 10%", quantity: 1, unit: "LS", unitCost: 14800, sortOrder: 0 },
];

export const extraPayments: Payment[] = [
  {
    id: "pay_r1",
    invoiceId: "inv_hart_dry",
    amount: 2400,
    method: "ACH",
    paidAt: "2026-07-28",
    reference: "Summit Claims — extraction",
  },
  {
    id: "pay_r2",
    invoiceId: "inv_whitfield_3",
    amount: 12000,
    method: "check",
    paidAt: "2026-08-12",
    reference: "Whitfield draw 3 — partial",
  },
  {
    id: "pay_r3",
    invoiceId: "inv_patel",
    amount: 19200,
    method: "ACH",
    paidAt: "2026-04-18",
    reference: "Patel insurance proceeds",
  },
  {
    id: "pay_r4",
    invoiceId: "inv_nguyen",
    amount: 22100,
    method: "check",
    paidAt: "2026-04-08",
    reference: "Nguyen #1182",
  },
  {
    id: "pay_r5",
    invoiceId: "inv_nash",
    amount: 24600,
    method: "ACH",
    paidAt: "2026-05-26",
    reference: "Nash final",
  },
  {
    id: "pay_r6",
    invoiceId: "inv_copper",
    amount: 9300,
    method: "ACH",
    paidAt: "2026-05-12",
    reference: "Copperline retainage",
  },
];

export const extraEvents: ScheduleEvent[] = [
  {
    id: "evt_r1",
    title: "Alvarez shingle day",
    kind: "production",
    startsAt: "2026-08-20T14:00:00.000Z",
    endsAt: "2026-08-20T22:00:00.000Z",
    location: "2841 Forest St",
    assignee: "Tom Brennan",
    opportunityId: null,
    jobId: "job_alvarez_roof",
    clientId: null,
    notes: "South slope. Dana is out of town — photos to her phone.",
  },
  {
    id: "evt_r2",
    title: "Ellison kitchen walk",
    kind: "site_walk",
    startsAt: "2026-08-19T15:00:00.000Z",
    endsAt: "2026-08-19T16:00:00.000Z",
    location: "840 S Franklin St",
    assignee: "Elena Voss",
    opportunityId: "opp_ellison_kit",
    jobId: null,
    clientId: null,
    notes: "Brook the realtor is coming.",
  },
  {
    id: "evt_r3",
    title: "Blake cabinet delivery",
    kind: "production",
    startsAt: "2026-08-21T14:00:00.000Z",
    endsAt: "2026-08-21T18:00:00.000Z",
    location: "1374 Madison St",
    assignee: "Maya Chen",
    opportunityId: null,
    jobId: "job_blake_kitchen",
    clientId: null,
    notes: "Nora wants to see the island before we set it.",
  },
  {
    id: "evt_r4",
    title: "Calder punch",
    kind: "punch",
    startsAt: "2026-08-22T16:00:00.000Z",
    endsAt: "2026-08-22T17:30:00.000Z",
    location: "1844 Grove St, Boulder",
    assignee: "Luis Ortega",
    opportunityId: null,
    jobId: "job_calder_siding",
    clientId: null,
    notes: "North caulk and two wraps. Bring the window number.",
  },
  {
    id: "evt_r5",
    title: "Brooks HOA walk",
    kind: "site_walk",
    startsAt: "2026-08-26T15:00:00.000Z",
    endsAt: "2026-08-26T16:00:00.000Z",
    location: "3480 S Broadway, Englewood",
    assignee: "Priya Shah",
    opportunityId: "opp_brooks_ext",
    jobId: null,
    clientId: null,
    notes: "She needs a number before the meeting.",
  },
  {
    id: "evt_r6",
    title: "Hart rebuild walk with Nina",
    kind: "inspection",
    startsAt: "2026-08-21T17:00:00.000Z",
    endsAt: "2026-08-21T18:00:00.000Z",
    location: "3428 Osceola St",
    assignee: "Elena Voss",
    opportunityId: "opp_hart_rebuild",
    jobId: "job_hart_water",
    clientId: null,
    notes: "Contents list before we price millwork.",
  },
  {
    id: "evt_r7",
    title: "Redmond permit with Hale + Moss",
    kind: "meeting",
    startsAt: "2026-08-27T16:00:00.000Z",
    endsAt: "2026-08-27T17:00:00.000Z",
    location: "Hale + Moss office",
    assignee: "Maya Chen",
    opportunityId: "opp_redmond_add",
    jobId: "job_redmond_add",
    clientId: "cli_hale",
    notes: "Sam has the structural comments.",
  },
  {
    id: "evt_r8",
    title: "Whitfield mechanical rough",
    kind: "production",
    startsAt: "2026-08-24T14:00:00.000Z",
    endsAt: "2026-08-24T22:00:00.000Z",
    location: "860 S University Blvd",
    assignee: "Tom Brennan",
    opportunityId: null,
    jobId: "job_whitfield_bsmt",
    clientId: null,
    notes: "Occupied house. Keep the upstairs closed.",
  },
];

export const extraPhotos: JobPhoto[] = [
  {
    id: "ph_r1",
    jobId: "job_alvarez_roof",
    caption: "Park Hill south slope after tear-off. Ice-and-water in the valleys.",
    category: "progress",
    takenAt: "2026-08-18",
    imageUrl: "https://images.unsplash.com/photo-1632778149955-e80f8ceca2e8?auto=format&fit=crop&w=1400&q=80",
    storagePath: null,
  },
  {
    id: "ph_r2",
    jobId: "job_alvarez_roof",
    caption: "Existing shingles before tear-off. Hail bruising on the south.",
    category: "before",
    takenAt: "2026-07-14",
    imageUrl: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1400&q=80",
    storagePath: null,
  },
  {
    id: "ph_r3",
    jobId: "job_hart_water",
    caption: "Highlands kitchen after extraction. Cabinets are a total loss.",
    category: "issue",
    takenAt: "2026-07-04",
    imageUrl: "https://images.unsplash.com/photo-1556912173-3bb406ef7e77?auto=format&fit=crop&w=1400&q=80",
    storagePath: null,
  },
  {
    id: "ph_r4",
    jobId: "job_blake_kitchen",
    caption: "Congress Park kitchen demo. Temporary kitchen in the dining room.",
    category: "progress",
    takenAt: "2026-07-08",
    imageUrl: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=1400&q=80",
    storagePath: null,
  },
  {
    id: "ph_r5",
    jobId: "job_calder_siding",
    caption: "Boulder north elevation at punch. Two window wraps remaining.",
    category: "progress",
    takenAt: "2026-08-15",
    imageUrl: "https://images.unsplash.com/photo-1600585154340-0ef3c08c08be?auto=format&fit=crop&w=1400&q=80",
    storagePath: null,
  },
  {
    id: "ph_r6",
    jobId: "job_nguyen_windows",
    caption: "Baker street — after. New units, old brick returned.",
    category: "after",
    takenAt: "2026-03-28",
    imageUrl: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1400&q=80",
    storagePath: null,
  },
  {
    id: "ph_r7",
    jobId: "job_whitfield_bsmt",
    caption: "Bonnie Brae basement framing. Mechanical rough next week.",
    category: "progress",
    takenAt: "2026-08-10",
    imageUrl: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1400&q=80",
    storagePath: null,
  },
  {
    id: "ph_r8",
    jobId: "job_nash_deck",
    caption: "Golden deck after stain. Warranty packet mailed.",
    category: "after",
    takenAt: "2026-05-16",
    imageUrl: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=80",
    storagePath: null,
  },
];
