import type { JobInsurance } from "@/lib/insurance";

/** Northline sample claims so the insurance desk has supplements and checks before a company connects Postgres. */
export const extraJobInsurance: JobInsurance[] = [
  {
    id: "ins_alvarez",
    jobId: "job_alvarez_roof",
    carrier: "State Farm",
    claimNumber: "SF-26-44821",
    policyNumber: "HO-992184",
    dateOfLoss: "2026-06-28",
    peril: "hail",
    status: "depreciation",
    deductible: 2500,
    rcv: 31200,
    acv: 27400,
    depreciation: 3800,
    recoverable: true,
    overheadProfit: 0,
    mortgageCompany: "Chase",
    loanNumber: "441902",
    adjusterName: "Al Brennan",
    adjusterEmail: "al@summitclaims.co",
    adjusterPhone: "(720) 555-8801",
    notes: "ACV check is with the mortgage company. Depreciation releases after the completion photos.",
    supplements: [
      {
        id: "sup_alvarez_ridge",
        title: "Ridge vent and hip cap",
        status: "approved",
        requested: 1800,
        approved: 1640,
        submittedAt: "2026-07-18",
        decidedAt: "2026-07-29",
        notes: "Al approved the ridge vent. Hip cap came in short $160.",
      },
    ],
    checks: [
      {
        id: "chk_alvarez_acv",
        kind: "acv",
        payee: "mortgage",
        amount: 24900,
        receivedAt: "2026-08-02",
        reference: "4412",
        supplementId: null,
        notes: "ACV less deductible. Chase is holding it.",
      },
    ],
    updatedAt: "2026-08-02T15:00:00.000Z",
  },
  {
    id: "ins_hart",
    jobId: "job_hart_water",
    carrier: "Travelers",
    claimNumber: "TRV-884120",
    policyNumber: "HO-220184",
    dateOfLoss: "2026-06-11",
    peril: "water",
    status: "approved",
    deductible: 1000,
    rcv: 41200,
    acv: 36100,
    depreciation: 5100,
    recoverable: true,
    overheadProfit: 4200,
    mortgageCompany: "",
    loanNumber: "",
    adjusterName: "Nina Cho",
    adjusterEmail: "nina@summitclaims.co",
    adjusterPhone: "(720) 555-8808",
    notes: "Dry-out is approved. Cabinet supplement is on the rebuild job.",
    supplements: [],
    checks: [
      {
        id: "chk_hart_acv",
        kind: "acv",
        payee: "homeowner",
        amount: 35100,
        receivedAt: "2026-07-02",
        reference: "7719",
        supplementId: null,
        notes: "",
      },
    ],
    updatedAt: "2026-07-02T18:00:00.000Z",
  },
  {
    id: "ins_hart_rebuild",
    jobId: "job_lead_opp_hart_rebuild",
    carrier: "Travelers",
    claimNumber: "TRV-884120",
    policyNumber: "HO-220184",
    dateOfLoss: "2026-06-11",
    peril: "water",
    status: "supplementing",
    deductible: 0,
    rcv: 28000,
    acv: 28000,
    depreciation: 0,
    recoverable: true,
    overheadProfit: 2800,
    mortgageCompany: "",
    loanNumber: "",
    adjusterName: "Nina Cho",
    adjusterEmail: "nina@summitclaims.co",
    adjusterPhone: "(720) 555-8808",
    notes: "Deductible was taken on the dry-out. Nina still wants the contents list before millwork.",
    supplements: [
      {
        id: "sup_hart_cabinets",
        title: "Cabinet rebuild",
        status: "submitted",
        requested: 6400,
        approved: 0,
        submittedAt: "2026-08-20",
        decidedAt: null,
        notes: "Waiting on Nina.",
      },
    ],
    checks: [],
    updatedAt: "2026-08-20T16:00:00.000Z",
  },
  {
    id: "ins_pell",
    jobId: "job_lead_opp_pell_roof",
    carrier: "State Farm",
    claimNumber: "SF-26-51002",
    policyNumber: "HO-104488",
    dateOfLoss: "2026-07-30",
    peril: "hail",
    status: "supplementing",
    deductible: 1000,
    rcv: 21400,
    acv: 18600,
    depreciation: 2800,
    recoverable: true,
    overheadProfit: 0,
    mortgageCompany: "Wells Fargo",
    loanNumber: "88211",
    adjusterName: "Al Brennan",
    adjusterEmail: "al@summitclaims.co",
    adjusterPhone: "(720) 555-8801",
    notes: "Al wants the two skylights on a supplement before Drew signs.",
    supplements: [
      {
        id: "sup_pell_skylight",
        title: "Two skylights",
        status: "draft",
        requested: 2800,
        approved: 0,
        submittedAt: null,
        decidedAt: null,
        notes: "Photos are on the job. Not sent yet.",
      },
    ],
    checks: [],
    updatedAt: "2026-08-18T14:00:00.000Z",
  },
  {
    id: "ins_ortiz",
    jobId: "job_ortiz_hail",
    carrier: "Allstate",
    claimNumber: "AL-339104",
    policyNumber: "HO-77301",
    dateOfLoss: "2026-07-14",
    peril: "hail",
    status: "supplementing",
    deductible: 1500,
    rcv: 18600,
    acv: 15400,
    depreciation: 3200,
    recoverable: true,
    overheadProfit: 0,
    mortgageCompany: "US Bank",
    loanNumber: "19022",
    adjusterName: "Al Brennan",
    adjusterEmail: "al@summitclaims.co",
    adjusterPhone: "(720) 555-8801",
    notes: "Job stays on hold until the carrier releases the supplement.",
    supplements: [
      {
        id: "sup_ortiz_drip",
        title: "Drip edge and starter",
        status: "submitted",
        requested: 2200,
        approved: 0,
        submittedAt: "2026-08-26",
        decidedAt: null,
        notes: "",
      },
    ],
    checks: [],
    updatedAt: "2026-08-26T17:00:00.000Z",
  },
  {
    id: "ins_solano",
    jobId: "job_solano_fire",
    carrier: "USAA",
    claimNumber: "USAA-26-1184",
    policyNumber: "HO-55021",
    dateOfLoss: "2026-07-19",
    peril: "fire",
    status: "approved",
    deductible: 5000,
    rcv: 186000,
    acv: 154000,
    depreciation: 32000,
    recoverable: true,
    overheadProfit: 18600,
    mortgageCompany: "Mr. Cooper",
    loanNumber: "66210",
    adjusterName: "Nina Cho",
    adjusterEmail: "nina@summitclaims.co",
    adjusterPhone: "(720) 555-8808",
    notes: "Structure is sound. Contents pack-out stays with the owner.",
    supplements: [
      {
        id: "sup_solano_smoke",
        title: "Smoke seal and HVAC clean",
        status: "partial",
        requested: 9400,
        approved: 7100,
        submittedAt: "2026-08-06",
        decidedAt: "2026-08-19",
        notes: "HVAC clean approved. Smoke seal cut back.",
      },
    ],
    checks: [
      {
        id: "chk_solano_acv",
        kind: "acv",
        payee: "split",
        amount: 149000,
        receivedAt: "2026-08-22",
        reference: "2201",
        supplementId: null,
        notes: "Mortgage and homeowner split.",
      },
    ],
    updatedAt: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "ins_patel",
    jobId: "job_patel_roof",
    carrier: "Liberty Mutual",
    claimNumber: "LM-104488",
    policyNumber: "HO-30012",
    dateOfLoss: "2026-02-02",
    peril: "hail",
    status: "closed",
    deductible: 1000,
    rcv: 19200,
    acv: 17100,
    depreciation: 2100,
    recoverable: true,
    overheadProfit: 0,
    mortgageCompany: "",
    loanNumber: "",
    adjusterName: "",
    adjusterEmail: "",
    adjusterPhone: "",
    notes: "Depreciation released with the completion photos.",
    supplements: [],
    checks: [
      {
        id: "chk_patel_acv",
        kind: "acv",
        payee: "contractor",
        amount: 16100,
        receivedAt: "2026-03-18",
        reference: "9088",
        supplementId: null,
        notes: "",
      },
      {
        id: "chk_patel_dep",
        kind: "depreciation",
        payee: "contractor",
        amount: 2100,
        receivedAt: "2026-04-11",
        reference: "9144",
        supplementId: null,
        notes: "",
      },
    ],
    updatedAt: "2026-04-11T15:00:00.000Z",
  },
];
