import type { CrmState } from "@/lib/types";

export const demoOps: Pick<
  CrmState,
  | "catalog"
  | "estimates"
  | "estimateLines"
  | "invoices"
  | "invoiceLines"
  | "payments"
  | "events"
  | "photos"
> = {
  catalog: [
    { id: "cat_sog", name: "Place & finish slab on grade", kind: "labor", unit: "sf", unitCost: 4.85, costCode: "03 30 00" },
    { id: "cat_mix", name: "Ready-mix 4000 psi", kind: "material", unit: "cy", unitCost: 168, costCode: "03 30 00" },
    { id: "cat_steel", name: "Structural steel package", kind: "subcontract", unit: "LS", unitCost: 2180000, costCode: "05 12 00" },
    { id: "cat_carp", name: "Rough carpentry", kind: "labor", unit: "lf", unitCost: 12.4, costCode: "06 10 00" },
    { id: "cat_insul", name: "Batt insulation", kind: "material", unit: "sf", unitCost: 1.85, costCode: "07 21 00" },
    { id: "cat_tpo", name: "TPO roofing", kind: "subcontract", unit: "sf", unitCost: 8.75, costCode: "07 54 00" },
    { id: "cat_doors", name: "HM doors & frames", kind: "material", unit: "ea", unitCost: 980, costCode: "08 11 00" },
    { id: "cat_dw", name: "Drywall hang, tape & finish", kind: "labor", unit: "sf", unitCost: 3.65, costCode: "09 29 00" },
    { id: "cat_paint", name: "Interior paint", kind: "labor", unit: "sf", unitCost: 1.95, costCode: "09 91 00" },
    { id: "cat_elec", name: "Electrical rough & trim", kind: "subcontract", unit: "sf", unitCost: 14.5, costCode: "26 05 00" },
    { id: "cat_plumb", name: "Plumbing rough", kind: "subcontract", unit: "sf", unitCost: 9.8, costCode: "22 00 00" },
    { id: "cat_hvac", name: "HVAC package", kind: "subcontract", unit: "sf", unitCost: 18.2, costCode: "23 00 00" },
    { id: "cat_temp", name: "Temporary facilities", kind: "allowance", unit: "mo", unitCost: 4200, costCode: "01 50 00" },
    { id: "cat_crane", name: "Tower crane", kind: "equipment", unit: "mo", unitCost: 28500, costCode: "01 54 00" },
    { id: "cat_demo", name: "Selective demolition", kind: "labor", unit: "sf", unitCost: 6.4, costCode: "02 41 00" },
    { id: "cat_gc", name: "General conditions", kind: "allowance", unit: "LS", unitCost: 1240000, costCode: "01 11 00" },
    { id: "cat_mep_pkg", name: "MEP design-assist package", kind: "subcontract", unit: "LS", unitCost: 6850000, costCode: "21 00 00" },
    { id: "cat_env", name: "Envelope & waterproofing", kind: "subcontract", unit: "LS", unitCost: 1960000, costCode: "07 10 00" },
    { id: "cat_int", name: "Interiors package", kind: "subcontract", unit: "LS", unitCost: 3410000, costCode: "09 00 00" },
    { id: "cat_conc_pkg", name: "Concrete package", kind: "subcontract", unit: "LS", unitCost: 1240000, costCode: "03 00 00" },
  ],
  estimates: [
    {
      id: "est_imaging",
      number: "EST-1001",
      name: "St. Luke's Imaging Pavilion — GMP",
      clientId: "cli_luke",
      opportunityId: "opp_imaging",
      jobId: null,
      status: "sent",
      notes:
        "GMP based on 90% CDs. Alternate for MRI shielding listed as an allowance. Valid through Labor Day.",
      validUntil: "2026-09-07",
      sentAt: "2026-08-18T21:10:00.000Z",
      acceptedAt: null,
      createdAt: "2026-08-12T16:00:00.000Z",
    },
    {
      id: "est_rino",
      number: "EST-1002",
      name: "River North Apartments — working takeoff",
      clientId: "cli_peakwest",
      opportunityId: "opp_rino",
      jobId: null,
      status: "draft",
      notes: "Podium vs. wood-over-podium still open. Do not send until Thursday VE.",
      validUntil: "2026-09-11",
      sentAt: null,
      acceptedAt: null,
      createdAt: "2026-08-16T15:20:00.000Z",
    },
    {
      id: "est_cherry",
      number: "EST-1003",
      name: "Cherry Creek Boutique TI — Suite 400",
      clientId: "cli_copperline",
      opportunityId: "opp_cherry_ti",
      jobId: null,
      status: "accepted",
      notes: "Accepted verbally 8/19. Helen wants a Labor Day start.",
      validUntil: "2026-08-29",
      sentAt: "2026-08-17T18:00:00.000Z",
      acceptedAt: "2026-08-19T15:10:00.000Z",
      createdAt: "2026-08-14T19:30:00.000Z",
    },
    {
      id: "est_mob",
      number: "EST-1004",
      name: "Cherry Creek MOB — contract SOV",
      clientId: "cli_meridian",
      opportunityId: "opp_mob",
      jobId: "job_mob",
      status: "accepted",
      notes: "Schedule of values used for progress billing. App 4 is the current invoice.",
      validUntil: null,
      sentAt: "2026-04-02T17:00:00.000Z",
      acceptedAt: "2026-04-18T16:00:00.000Z",
      createdAt: "2026-03-28T14:00:00.000Z",
    },
  ],
  estimateLines: [
    { id: "el_img_1", estimateId: "est_imaging", catalogItemId: "cat_conc_pkg", description: "Concrete package", quantity: 1, unit: "LS", unitCost: 1240000, sortOrder: 0 },
    { id: "el_img_2", estimateId: "est_imaging", catalogItemId: "cat_steel", description: "Structural steel package", quantity: 1, unit: "LS", unitCost: 2180000, sortOrder: 1 },
    { id: "el_img_3", estimateId: "est_imaging", catalogItemId: "cat_env", description: "Envelope & waterproofing", quantity: 1, unit: "LS", unitCost: 1960000, sortOrder: 2 },
    { id: "el_img_4", estimateId: "est_imaging", catalogItemId: "cat_int", description: "Interiors package", quantity: 1, unit: "LS", unitCost: 3410000, sortOrder: 3 },
    { id: "el_img_5", estimateId: "est_imaging", catalogItemId: "cat_mep_pkg", description: "MEP design-assist package", quantity: 1, unit: "LS", unitCost: 6850000, sortOrder: 4 },
    { id: "el_img_6", estimateId: "est_imaging", catalogItemId: "cat_gc", description: "General conditions", quantity: 1, unit: "LS", unitCost: 1240000, sortOrder: 5 },
    { id: "el_rino_1", estimateId: "est_rino", catalogItemId: "cat_sog", description: "Place & finish slab on grade", quantity: 42000, unit: "sf", unitCost: 4.85, sortOrder: 0 },
    { id: "el_rino_2", estimateId: "est_rino", catalogItemId: "cat_steel", description: "Podium structural steel", quantity: 1, unit: "LS", unitCost: 3640000, sortOrder: 1 },
    { id: "el_rino_3", estimateId: "est_rino", catalogItemId: "cat_carp", description: "Rough carpentry", quantity: 18600, unit: "lf", unitCost: 12.4, sortOrder: 2 },
    { id: "el_rino_4", estimateId: "est_rino", catalogItemId: "cat_tpo", description: "TPO roofing", quantity: 28000, unit: "sf", unitCost: 8.75, sortOrder: 3 },
    { id: "el_rino_5", estimateId: "est_rino", catalogItemId: "cat_hvac", description: "HVAC package", quantity: 186000, unit: "sf", unitCost: 18.2, sortOrder: 4 },
    { id: "el_rino_6", estimateId: "est_rino", catalogItemId: "cat_crane", description: "Tower crane", quantity: 8, unit: "mo", unitCost: 28500, sortOrder: 5 },
    { id: "el_ch_1", estimateId: "est_cherry", catalogItemId: "cat_demo", description: "Selective demolition", quantity: 8200, unit: "sf", unitCost: 6.4, sortOrder: 0 },
    { id: "el_ch_2", estimateId: "est_cherry", catalogItemId: "cat_dw", description: "Drywall hang, tape & finish", quantity: 16400, unit: "sf", unitCost: 3.65, sortOrder: 1 },
    { id: "el_ch_3", estimateId: "est_cherry", catalogItemId: "cat_paint", description: "Interior paint", quantity: 16400, unit: "sf", unitCost: 1.95, sortOrder: 2 },
    { id: "el_ch_4", estimateId: "est_cherry", catalogItemId: "cat_elec", description: "Electrical rough & trim", quantity: 8200, unit: "sf", unitCost: 14.5, sortOrder: 3 },
    { id: "el_ch_5", estimateId: "est_cherry", catalogItemId: "cat_doors", description: "HM doors & frames", quantity: 18, unit: "ea", unitCost: 980, sortOrder: 4 },
    { id: "el_ch_6", estimateId: "est_cherry", catalogItemId: "cat_temp", description: "Temporary facilities", quantity: 4, unit: "mo", unitCost: 4200, sortOrder: 5 },
    { id: "el_mob_1", estimateId: "est_mob", catalogItemId: "cat_conc_pkg", description: "Foundations & structure concrete", quantity: 1, unit: "LS", unitCost: 4120000, sortOrder: 0 },
    { id: "el_mob_2", estimateId: "est_mob", catalogItemId: "cat_steel", description: "Structural steel & misc metals", quantity: 1, unit: "LS", unitCost: 5680000, sortOrder: 1 },
    { id: "el_mob_3", estimateId: "est_mob", catalogItemId: "cat_env", description: "Envelope & waterproofing", quantity: 1, unit: "LS", unitCost: 2740000, sortOrder: 2 },
    { id: "el_mob_4", estimateId: "est_mob", catalogItemId: "cat_mep_pkg", description: "MEP design-assist package", quantity: 1, unit: "LS", unitCost: 9420000, sortOrder: 3 },
    { id: "el_mob_5", estimateId: "est_mob", catalogItemId: "cat_int", description: "Interiors package", quantity: 1, unit: "LS", unitCost: 4860000, sortOrder: 4 },
    { id: "el_mob_6", estimateId: "est_mob", catalogItemId: "cat_gc", description: "General conditions & fee", quantity: 1, unit: "LS", unitCost: 4380000, sortOrder: 5 },
  ],
  invoices: [
    {
      id: "inv_mob_app4",
      number: "INV-2001",
      name: "Cherry Creek MOB — Application 4",
      clientId: "cli_meridian",
      jobId: "job_mob",
      estimateId: "est_mob",
      status: "partial",
      issuedAt: "2026-08-01",
      dueAt: "2026-08-31",
      notes: "Progress billing through July. Steel erection 60%. Storefront starting next week.",
    },
    {
      id: "inv_wynkoop",
      number: "INV-2002",
      name: "Wynkoop Mixed-Use — retainage release",
      clientId: "cli_meridian",
      jobId: "job_mixed",
      estimateId: null,
      status: "sent",
      issuedAt: "2026-08-08",
      dueAt: "2026-08-22",
      notes: "Retainage held pending elevator inspection and TCO.",
    },
    {
      id: "inv_cherry_dep",
      number: "INV-2003",
      name: "Cherry Creek TI — 10% deposit",
      clientId: "cli_copperline",
      jobId: null,
      estimateId: "est_cherry",
      status: "paid",
      issuedAt: "2026-08-19",
      dueAt: "2026-08-26",
      notes: "Deposit against accepted proposal EST-1003.",
    },
    {
      id: "inv_rec_precon",
      number: "INV-2004",
      name: "Aurora Rec Center — precon fee",
      clientId: "cli_aurora",
      jobId: "job_rec",
      estimateId: null,
      status: "overdue",
      issuedAt: "2026-07-15",
      dueAt: "2026-08-14",
      notes: "Preconstruction services. City AP is waiting on a PO revision.",
    },
  ],
  invoiceLines: [
    { id: "il_1", invoiceId: "inv_mob_app4", description: "Structural steel — 60% complete", quantity: 0.6, unit: "LS", unitCost: 5680000, sortOrder: 0 },
    { id: "il_2", invoiceId: "inv_mob_app4", description: "Concrete package — 85% complete", quantity: 0.85, unit: "LS", unitCost: 4120000, sortOrder: 1 },
    { id: "il_3", invoiceId: "inv_mob_app4", description: "General conditions — July", quantity: 1, unit: "mo", unitCost: 186000, sortOrder: 2 },
    { id: "il_4", invoiceId: "inv_wynkoop", description: "Retainage release — 5% of contract", quantity: 1, unit: "LS", unitCost: 410000, sortOrder: 0 },
    { id: "il_5", invoiceId: "inv_cherry_dep", description: "Mobilization & deposit — Suite 400", quantity: 1, unit: "LS", unitCost: 210000, sortOrder: 0 },
    { id: "il_6", invoiceId: "inv_rec_precon", description: "Preconstruction services — May–July", quantity: 1, unit: "LS", unitCost: 85000, sortOrder: 0 },
  ],
  payments: [
    {
      id: "pay_1",
      invoiceId: "inv_mob_app4",
      amount: 2140000,
      method: "ACH",
      paidAt: "2026-08-12",
      reference: "Meridian draw 4 — partial",
    },
    {
      id: "pay_2",
      invoiceId: "inv_cherry_dep",
      amount: 210000,
      method: "check",
      paidAt: "2026-08-19",
      reference: "Copperline #4418",
    },
  ],
  events: [
    {
      id: "evt_1",
      title: "Wynkoop OAC",
      kind: "meeting",
      startsAt: "2026-08-18T15:00:00.000Z",
      endsAt: "2026-08-18T16:00:00.000Z",
      location: "Wynkoop trailer",
      assignee: "Elena Voss",
      opportunityId: null,
      jobId: "job_mixed",
      clientId: "cli_meridian",
      notes: "Punch at 38 items. Elevator inspector Friday.",
    },
    {
      id: "evt_2",
      title: "Front Range freezer layout walk",
      kind: "site_walk",
      startsAt: "2026-08-19T16:00:00.000Z",
      endsAt: "2026-08-19T18:00:00.000Z",
      location: "Commerce City, CO",
      assignee: "Maya Chen",
      opportunityId: "opp_cold",
      jobId: null,
      clientId: "cli_frontrange",
      notes: "Confirm panel vendor and after-hours pour window.",
    },
    {
      id: "evt_3",
      title: "Imaging pavilion GMP follow-up",
      kind: "meeting",
      startsAt: "2026-08-19T20:00:00.000Z",
      endsAt: "2026-08-19T20:45:00.000Z",
      location: "Teams",
      assignee: "Jordan Hale",
      opportunityId: "opp_imaging",
      jobId: null,
      clientId: "cli_luke",
      notes: "Renee reviewing bid tab. Proposal EST-1001 is out.",
    },
    {
      id: "evt_4",
      title: "River North VE workshop",
      kind: "meeting",
      startsAt: "2026-08-20T15:00:00.000Z",
      endsAt: "2026-08-20T17:30:00.000Z",
      location: "Peak West — Boulder",
      assignee: "Priya Shah",
      opportunityId: "opp_rino",
      jobId: null,
      clientId: "cli_peakwest",
      notes: "Wood-frame vs. podium cost delta.",
    },
    {
      id: "evt_5",
      title: "MOB steel inspection",
      kind: "inspection",
      startsAt: "2026-08-20T19:00:00.000Z",
      endsAt: "2026-08-20T21:00:00.000Z",
      location: "Cherry Creek MOB",
      assignee: "Tom Brennan",
      opportunityId: null,
      jobId: "job_mob",
      clientId: "cli_meridian",
      notes: "City special inspector on moment frames.",
    },
    {
      id: "evt_6",
      title: "Imaging bid due — recap",
      kind: "meeting",
      startsAt: "2026-08-21T14:00:00.000Z",
      endsAt: "2026-08-21T15:00:00.000Z",
      location: "Northline office",
      assignee: "Maya Chen",
      opportunityId: "opp_imaging",
      jobId: null,
      clientId: null,
      notes: "Internal recap. Bid due today.",
    },
    {
      id: "evt_7",
      title: "Wynkoop elevator inspection",
      kind: "inspection",
      startsAt: "2026-08-21T16:00:00.000Z",
      endsAt: "2026-08-21T18:00:00.000Z",
      location: "Wynkoop Mixed-Use",
      assignee: "Elena Voss",
      opportunityId: null,
      jobId: "job_mixed",
      clientId: null,
      notes: "Last gate before TCO.",
    },
    {
      id: "evt_8",
      title: "DPS West High — shop overheads",
      kind: "production",
      startsAt: "2026-08-17T14:00:00.000Z",
      endsAt: "2026-08-17T22:00:00.000Z",
      location: "West Colfax",
      assignee: "Tom Brennan",
      opportunityId: null,
      jobId: "job_school",
      clientId: "cli_dps",
      notes: "Occupied campus. After-hours only.",
    },
    {
      id: "evt_9",
      title: "Cherry Creek TI staffing review",
      kind: "pre_bid",
      startsAt: "2026-08-20T21:00:00.000Z",
      endsAt: "2026-08-20T21:30:00.000Z",
      location: "Call with Helen",
      assignee: "Jordan Hale",
      opportunityId: "opp_cherry_ti",
      jobId: null,
      clientId: "cli_copperline",
      notes: "Send 14-week look-ahead. Labor Day start.",
    },
    {
      id: "evt_10",
      title: "Wynkoop punch walk",
      kind: "punch",
      startsAt: "2026-08-22T15:00:00.000Z",
      endsAt: "2026-08-22T18:00:00.000Z",
      location: "Wynkoop Mixed-Use",
      assignee: "Elena Voss",
      opportunityId: null,
      jobId: "job_mixed",
      clientId: null,
      notes: "Owner punch with Ava.",
    },
  ],
  photos: [
    {
      id: "ph_1",
      jobId: "job_mob",
      caption: "Level 3 deck pour looking west toward Cherry Creek.",
      category: "progress",
      takenAt: "2026-08-14",
      imageUrl:
        "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1400&q=80",
      storagePath: null,
    },
    {
      id: "ph_2",
      jobId: "job_mob",
      caption: "Steel erection — moment frame at grid D.",
      category: "progress",
      takenAt: "2026-08-11",
      imageUrl:
        "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1400&q=80",
      storagePath: null,
    },
    {
      id: "ph_3",
      jobId: "job_mob",
      caption: "Site logistics before the tower crane jumped.",
      category: "before",
      takenAt: "2026-06-04",
      imageUrl:
        "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1400&q=80",
      storagePath: null,
    },
    {
      id: "ph_4",
      jobId: "job_mixed",
      caption: "Lobby millwork punch — waiting on elevator cab finishes.",
      category: "issue",
      takenAt: "2026-08-16",
      imageUrl:
        "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=80",
      storagePath: null,
    },
    {
      id: "ph_5",
      jobId: "job_mixed",
      caption: "Unit 1204 after paint — ready for owner walk.",
      category: "after",
      takenAt: "2026-08-18",
      imageUrl:
        "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=80",
      storagePath: null,
    },
    {
      id: "ph_6",
      jobId: "job_school",
      caption: "CTE shop overheads — after-hours set.",
      category: "progress",
      takenAt: "2026-08-17",
      imageUrl:
        "https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=1400&q=80",
      storagePath: null,
    },
    {
      id: "ph_7",
      jobId: "job_school",
      caption: "Existing shop floor before demo. Dust control in place.",
      category: "before",
      takenAt: "2026-01-08",
      imageUrl:
        "https://images.unsplash.com/photo-1503384154456-cc0bfd9ab34a?auto=format&fit=crop&w=1400&q=80",
      storagePath: null,
    },
  ],
};
