import type { Activity, Client, Contact, Opportunity, Task } from "@/lib/types";
import { type JobDraft } from "@/lib/job-record";

export const extraClients: Client[] = [
  {
    id: "cli_hale",
    name: "Hale + Moss Architects",
    type: "architect",
    city: "Denver",
    state: "CO",
    notes: "Residential specifier. Puts Northline on additions when closeout photos look clean.",
  },
  {
    id: "cli_copperline",
    name: "Copperline Retail Group",
    type: "owner",
    city: "Cherry Creek",
    state: "CO",
    notes: "Occasional commercial TI. Not the core book — homeowners are.",
  },
  {
    id: "cli_summit",
    name: "Summit Claims Group",
    type: "insurance",
    city: "Denver",
    state: "CO",
    notes: "Independent adjusters. Al sends hail and water files when the homeowner has not picked a contractor.",
  },
  {
    id: "cli_parkhill_re",
    name: "Park Hill Realty",
    type: "realtor",
    city: "Denver",
    state: "CO",
    notes: "Brook sends pre-list kitchens and roofs. Referral fee is not on the table; speed is.",
  },
];

function homeowner(
  id: string,
  name: string,
  email: string,
  phone: string,
  ownerStaffId: string,
  title = "Homeowner"
): Contact {
  return {
    id,
    clientId: null,
    name,
    title,
    email,
    phone,
    ownerStaffId,
    isReferralPartner: false,
  };
}

export const extraContacts: Contact[] = [
  homeowner("con_dana", "Dana Alvarez", "dana.alvarez.parkhill@gmail.com", "(303) 555-2140", "staff_elena"),
  homeowner("con_marcus", "Marcus Ellison", "marcus.ellison.wp@gmail.com", "(303) 555-2188", "staff_elena"),
  homeowner("con_owen", "Owen Hart", "owen.hart.highlands@gmail.com", "(720) 555-3301", "staff_elena"),
  homeowner("con_ivy", "Ivy Calder", "ivy.calder.boulder@gmail.com", "(303) 555-4412", "staff_luis"),
  homeowner("con_theo", "Theo Marsh", "theo.marsh.lohi@gmail.com", "(720) 555-1194", "staff_maya"),
  homeowner("con_mira", "Mira Solano", "mira.solano.aurora@gmail.com", "(720) 555-6620", "staff_maya"),
  homeowner("con_greg", "Greg Nash", "greg.nash.golden@gmail.com", "(303) 555-7781", "staff_luis"),
  homeowner("con_cleo", "Cleo Redmond", "cleo.redmond.cc@gmail.com", "(303) 555-9012", "staff_maya"),
  homeowner("con_ross", "Ross Patel", "ross.patel.stapleton@gmail.com", "(720) 555-4488", "staff_luis"),
  homeowner("con_nora", "Nora Blake", "nora.blake.congress@gmail.com", "(303) 555-5560", "staff_maya"),
  homeowner("con_ben", "Ben Whitfield", "ben.whitfield.bb@gmail.com", "(303) 555-6704", "staff_elena"),
  homeowner("con_cara", "Cara Nguyen", "cara.nguyen.baker@gmail.com", "(720) 555-2233", "staff_elena"),
  homeowner("con_sam_ortiz", "Sam Ortiz", "sam.ortiz.rino@gmail.com", "(303) 555-8890", "staff_luis"),
  homeowner("con_lina", "Lina Brooks", "lina.brooks.englewood@gmail.com", "(720) 555-3344", "staff_priya"),
  homeowner("con_drew", "Drew Pell", "drew.pell.lakewood@gmail.com", "(303) 555-4455", "staff_priya"),
  homeowner("con_max", "Max Voss", "max.voss.centennial@gmail.com", "(720) 555-5566", "staff_priya"),
  homeowner("con_joy", "Joy Park", "joy.park.hilltop@gmail.com", "(303) 555-6677", "staff_maya"),
  homeowner("con_wes", "Wes Calder", "wes.calder.louisville@gmail.com", "(303) 555-7788", "staff_priya"),
  {
    id: "con_hale_sam",
    clientId: "cli_hale",
    name: "Sam Moss",
    title: "Partner",
    email: "smoss@halemoss.com",
    phone: "(303) 555-3309",
    ownerStaffId: "staff_maya",
    isReferralPartner: true,
  },
  {
    id: "con_copper_helen",
    clientId: "cli_copperline",
    name: "Helen Cho",
    title: "Director of Construction",
    email: "helen@copperline.com",
    phone: "(303) 555-0914",
    ownerStaffId: "staff_jordan",
    isReferralPartner: false,
  },
  {
    id: "con_summit_al",
    clientId: "cli_summit",
    name: "Al Brennan",
    title: "Independent adjuster",
    email: "al@summitclaims.co",
    phone: "(720) 555-8801",
    ownerStaffId: "staff_priya",
    isReferralPartner: true,
  },
  {
    id: "con_summit_nina",
    clientId: "cli_summit",
    name: "Nina Cho",
    title: "Desk adjuster",
    email: "nina@summitclaims.co",
    phone: "(720) 555-8808",
    ownerStaffId: "staff_elena",
    isReferralPartner: true,
  },
  {
    id: "con_re_brook",
    clientId: "cli_parkhill_re",
    name: "Brook Ellison",
    title: "Listing agent",
    email: "brook@parkhillrealty.com",
    phone: "(303) 555-0194",
    ownerStaffId: "staff_priya",
    isReferralPartner: true,
  },
  {
    id: "con_re_kate",
    clientId: "cli_parkhill_re",
    name: "Kate Ruiz",
    title: "Buyer’s agent",
    email: "kate@parkhillrealty.com",
    phone: "(303) 555-0198",
    ownerStaffId: "staff_claire",
    isReferralPartner: true,
  },
  {
    id: "con_trade_ruiz",
    clientId: null,
    name: "David Ruiz",
    title: "Roofing subcontractor",
    email: "david@ruizroofing.co",
    phone: "(720) 555-2210",
    ownerStaffId: "staff_tom",
    isReferralPartner: false,
  },
  {
    id: "con_trade_vale",
    clientId: null,
    name: "Vale Dry-Out",
    title: "Water extraction",
    email: "dispatch@valedryout.com",
    phone: "(303) 555-7720",
    ownerStaffId: "staff_elena",
    isReferralPartner: false,
  },
];

export const extraOpportunities: Omit<Opportunity, "code">[] = [
  {
    id: "opp_alvarez_roof",
    name: "Alvarez hail roof — Park Hill",
    clientId: null,
    primaryContactId: "con_dana",
    stage: "awarded",
    value: 28400,
    bidDueAt: "2026-07-22",
    preBidWalkAt: "2026-07-14",
    location: "2841 Forest St, Denver, CO",
    projectType: "roofing",
    deliveryMethod: "insurance_claim",
    estimator: "Maya Chen",
    ownerStaffId: "staff_elena",
    originatorStaffId: "staff_priya",
    winProbability: 100,
    nextStep: "Sold. Production is on the job.",
    createdAt: "2026-07-08T15:00:00.000Z",
    leadSource: "referral",
    referralContactId: "con_summit_al",
  },
  {
    id: "opp_hart_water",
    name: "Hart water restoration — Highlands",
    clientId: null,
    primaryContactId: "con_owen",
    stage: "awarded",
    value: 41200,
    bidDueAt: "2026-06-30",
    preBidWalkAt: null,
    location: "3428 Osceola St, Denver, CO",
    projectType: "restoration",
    deliveryMethod: "insurance_claim",
    estimator: "Elena Voss",
    ownerStaffId: "staff_elena",
    winProbability: 100,
    nextStep: "Dry-out complete. Rebuild in progress.",
    createdAt: "2026-06-18T14:20:00.000Z",
  },
  {
    id: "opp_solano_fire",
    name: "Solano fire restoration — Aurora",
    clientId: null,
    primaryContactId: "con_mira",
    stage: "awarded",
    value: 186000,
    bidDueAt: "2026-08-12",
    preBidWalkAt: "2026-08-04",
    location: "12844 E 13th Ave, Aurora, CO",
    projectType: "restoration",
    deliveryMethod: "insurance_claim",
    estimator: "Maya Chen",
    ownerStaffId: "staff_maya",
    winProbability: 100,
    nextStep: "Sold. Precon starts October.",
    createdAt: "2026-07-22T16:40:00.000Z",
  },
  {
    id: "opp_whitfield_bsmt",
    name: "Whitfield basement finish — Bonnie Brae",
    clientId: null,
    primaryContactId: "con_ben",
    stage: "awarded",
    value: 64000,
    bidDueAt: "2026-05-20",
    preBidWalkAt: "2026-05-12",
    location: "860 S University Blvd, Denver, CO",
    projectType: "remodel",
    deliveryMethod: "fixed_price",
    estimator: "Elena Voss",
    ownerStaffId: "staff_elena",
    originatorStaffId: "staff_claire",
    winProbability: 100,
    nextStep: "Framing complete. Mechanical rough next week.",
    createdAt: "2026-05-02T15:10:00.000Z",
    leadSource: "referral",
    referralContactId: "con_re_kate",
  },
  {
    id: "opp_calder_siding",
    name: "Calder siding & trim — Boulder",
    clientId: null,
    primaryContactId: "con_ivy",
    stage: "awarded",
    value: 31800,
    bidDueAt: "2026-04-28",
    preBidWalkAt: "2026-04-21",
    location: "1844 Grove St, Boulder, CO",
    projectType: "exterior",
    deliveryMethod: "fixed_price",
    estimator: "Luis Ortega",
    ownerStaffId: "staff_luis",
    winProbability: 100,
    nextStep: "Punch: north elevation caulk and two window wraps.",
    createdAt: "2026-04-10T17:00:00.000Z",
  },
  {
    id: "opp_patel_roof",
    name: "Patel roof replacement — Stapleton",
    clientId: null,
    primaryContactId: "con_ross",
    stage: "awarded",
    value: 19200,
    bidDueAt: "2026-03-18",
    preBidWalkAt: "2026-03-11",
    location: "8124 E 29th Ave, Denver, CO",
    projectType: "roofing",
    deliveryMethod: "insurance_claim",
    estimator: "Luis Ortega",
    ownerStaffId: "staff_luis",
    winProbability: 100,
    nextStep: "Closed. Warranty packet mailed.",
    createdAt: "2026-03-01T16:00:00.000Z",
  },
  {
    id: "opp_blake_kitchen",
    name: "Blake kitchen remodel — Congress Park",
    clientId: null,
    primaryContactId: "con_nora",
    stage: "awarded",
    value: 54000,
    bidDueAt: "2026-06-10",
    preBidWalkAt: "2026-06-02",
    location: "1374 Madison St, Denver, CO",
    projectType: "remodel",
    deliveryMethod: "fixed_price",
    estimator: "Maya Chen",
    ownerStaffId: "staff_maya",
    winProbability: 100,
    nextStep: "Cabinets land Thursday. Keep Nora off the old layout.",
    createdAt: "2026-05-22T18:20:00.000Z",
  },
  {
    id: "opp_nguyen_windows",
    name: "Nguyen window package — Baker",
    clientId: null,
    primaryContactId: "con_cara",
    stage: "awarded",
    value: 22100,
    bidDueAt: "2026-02-26",
    preBidWalkAt: "2026-02-18",
    location: "430 W 2nd Ave, Denver, CO",
    projectType: "exterior",
    deliveryMethod: "fixed_price",
    estimator: "Elena Voss",
    ownerStaffId: "staff_elena",
    winProbability: 100,
    nextStep: "Complete. One-year walk in February 2027.",
    createdAt: "2026-02-08T15:40:00.000Z",
  },
  {
    id: "opp_ortiz_hail",
    name: "Ortiz hail claim — RiNo",
    clientId: null,
    primaryContactId: "con_sam_ortiz",
    stage: "awarded",
    value: 16800,
    bidDueAt: "2026-08-04",
    preBidWalkAt: "2026-07-28",
    location: "3227 Larimer St, Denver, CO",
    projectType: "roofing",
    deliveryMethod: "insurance_claim",
    estimator: "Luis Ortega",
    ownerStaffId: "staff_luis",
    winProbability: 100,
    nextStep: "On hold until the carrier releases the supplement.",
    createdAt: "2026-07-20T14:00:00.000Z",
  },
  {
    id: "opp_redmond_add",
    name: "Redmond rear addition — Cherry Creek",
    clientId: null,
    primaryContactId: "con_cleo",
    stage: "awarded",
    value: 148000,
    bidDueAt: "2026-08-18",
    preBidWalkAt: "2026-08-08",
    location: "255 Steele St, Denver, CO",
    projectType: "addition",
    deliveryMethod: "fixed_price",
    estimator: "Maya Chen",
    ownerStaffId: "staff_maya",
    winProbability: 100,
    nextStep: "Permit set with Hale + Moss. Start after Labor Day.",
    createdAt: "2026-07-14T19:00:00.000Z",
  },
  {
    id: "opp_nash_deck",
    name: "Nash deck rebuild — Golden",
    clientId: null,
    primaryContactId: "con_greg",
    stage: "awarded",
    value: 24600,
    bidDueAt: "2026-04-02",
    preBidWalkAt: "2026-03-26",
    location: "710 10th St, Golden, CO",
    projectType: "exterior",
    deliveryMethod: "fixed_price",
    estimator: "Luis Ortega",
    ownerStaffId: "staff_luis",
    winProbability: 100,
    nextStep: "Complete. Stain warranty in the closeout folder.",
    createdAt: "2026-03-12T16:30:00.000Z",
  },
  {
    id: "opp_ellison_kit",
    name: "Ellison kitchen — Wash Park",
    clientId: null,
    primaryContactId: "con_marcus",
    stage: "estimating",
    value: 72000,
    bidDueAt: "2026-08-27",
    preBidWalkAt: "2026-08-19",
    location: "840 S Franklin St, Denver, CO",
    projectType: "remodel",
    deliveryMethod: "fixed_price",
    estimator: "Maya Chen",
    ownerStaffId: "staff_elena",
    originatorStaffId: "staff_priya",
    winProbability: 30,
    nextStep: "Price the island quartz and the pantry wall. Brook wants it listed by October.",
    createdAt: "2026-08-12T15:20:00.000Z",
    leadSource: "referral",
    referralContactId: "con_re_brook",
  },
  {
    id: "opp_marsh_bath",
    name: "Marsh primary bath — LoHi",
    clientId: null,
    primaryContactId: "con_theo",
    stage: "bid_submitted",
    value: 18600,
    bidDueAt: "2026-08-21",
    preBidWalkAt: "2026-08-14",
    location: "2215 16th St, Denver, CO",
    projectType: "remodel",
    deliveryMethod: "fixed_price",
    estimator: "Maya Chen",
    ownerStaffId: "staff_maya",
    winProbability: 45,
    nextStep: "Proposal is with Theo. He asked about a Friday start so he can work from home.",
    createdAt: "2026-08-06T17:10:00.000Z",
  },
  {
    id: "opp_brooks_ext",
    name: "Brooks paint & siding — Englewood",
    clientId: null,
    primaryContactId: "con_lina",
    stage: "pursuing",
    value: 24000,
    bidDueAt: "2026-09-04",
    preBidWalkAt: "2026-08-26",
    location: "3480 S Broadway, Englewood, CO",
    projectType: "exterior",
    deliveryMethod: "fixed_price",
    estimator: "Priya Shah",
    ownerStaffId: "staff_priya",
    winProbability: 15,
            nextStep: "Walk Wednesday. She wants a number before her HOA meeting.",
    createdAt: "2026-08-16T18:00:00.000Z",
    leadSource: "google",
    city: "Englewood",
    state: "CO",
  },
  {
    id: "opp_pell_roof",
    name: "Pell roof + gutters — Lakewood",
    clientId: null,
    primaryContactId: "con_drew",
    stage: "interview",
    value: 21400,
    bidDueAt: "2026-08-25",
    preBidWalkAt: "2026-08-17",
    location: "9600 W Jewell Ave, Lakewood, CO",
    projectType: "roofing",
    deliveryMethod: "insurance_claim",
    estimator: "Luis Ortega",
    ownerStaffId: "staff_luis",
    originatorStaffId: "staff_priya",
    winProbability: 65,
            nextStep: "Al at Summit wants a supplement on the two skylights. Call Drew after.",
    createdAt: "2026-08-10T16:00:00.000Z",
    leadSource: "referral",
    referralContactId: "con_summit_al",
    city: "Lakewood",
    state: "CO",
  },
  {
    id: "opp_voss_windows",
    name: "Voss window replacement — Centennial",
    clientId: null,
    primaryContactId: "con_max",
    stage: "pursuing",
    value: 16800,
    bidDueAt: "2026-09-10",
    preBidWalkAt: "2026-09-02",
    location: "6980 S Holly St, Centennial, CO",
    projectType: "exterior",
    deliveryMethod: "fixed_price",
    estimator: "Priya Shah",
    ownerStaffId: "staff_priya",
    winProbability: 15,
            nextStep: "Measure the south elevation. Max is comparing three GCs.",
    createdAt: "2026-08-15T14:40:00.000Z",
    leadSource: "website",
    city: "Centennial",
    state: "CO",
  },
  {
    id: "opp_park_kitchen",
    name: "Park kitchen — Hilltop",
    clientId: null,
    primaryContactId: "con_joy",
    stage: "interview",
    value: 68000,
    bidDueAt: "2026-08-28",
    preBidWalkAt: "2026-08-20",
    location: "210 Krameria St, Denver, CO",
    projectType: "remodel",
    deliveryMethod: "fixed_price",
    estimator: "Maya Chen",
    ownerStaffId: "staff_maya",
    winProbability: 65,
    nextStep: "Joy wants names of the last three kitchens, not a brochure. Send Blake photos.",
    createdAt: "2026-08-08T19:20:00.000Z",
  },
  {
    id: "opp_calder_win",
    name: "Calder window upsell — Boulder",
    clientId: null,
    primaryContactId: "con_ivy",
    stage: "pursuing",
    value: 14200,
    bidDueAt: "2026-09-08",
    preBidWalkAt: null,
    location: "1844 Grove St, Boulder, CO",
    projectType: "exterior",
    deliveryMethod: "fixed_price",
    estimator: "Luis Ortega",
    ownerStaffId: "staff_luis",
    winProbability: 15,
    nextStep: "Ivy asked during punch. Price the four west windows while the crew is still on site.",
    createdAt: "2026-08-17T15:00:00.000Z",
  },
  {
    id: "opp_hart_rebuild",
    name: "Hart kitchen rebuild after water",
    clientId: null,
    primaryContactId: "con_owen",
    stage: "estimating",
    value: 28000,
    bidDueAt: "2026-08-26",
    preBidWalkAt: null,
    location: "3428 Osceola St, Denver, CO",
    projectType: "restoration",
    deliveryMethod: "insurance_claim",
    estimator: "Elena Voss",
    ownerStaffId: "staff_elena",
    winProbability: 30,
    nextStep: "Cabinets were a total loss. Get Nina’s contents list before we price millwork.",
    createdAt: "2026-08-11T13:50:00.000Z",
  },
  {
    id: "opp_blake_bath",
    name: "Blake hall bath — Congress Park",
    clientId: null,
    primaryContactId: "con_nora",
    stage: "pursuing",
    value: 22000,
    bidDueAt: "2026-09-16",
    preBidWalkAt: "2026-09-03",
    location: "1374 Madison St, Denver, CO",
    projectType: "remodel",
    deliveryMethod: "fixed_price",
    estimator: "Maya Chen",
    ownerStaffId: "staff_maya",
    winProbability: 15,
    nextStep: "After the kitchen. Keep it warm; she does not want two crews overlapping.",
    createdAt: "2026-08-14T16:10:00.000Z",
  },
  {
    id: "opp_whitfield_kit",
    name: "Whitfield kitchen after basement",
    clientId: null,
    primaryContactId: "con_ben",
    stage: "bid_submitted",
    value: 58000,
    bidDueAt: "2026-08-24",
    preBidWalkAt: "2026-08-16",
    location: "860 S University Blvd, Denver, CO",
    projectType: "remodel",
    deliveryMethod: "fixed_price",
    estimator: "Maya Chen",
    ownerStaffId: "staff_elena",
    winProbability: 45,
    nextStep: "Proposal sent. Ben wants to start the day the basement punches.",
    createdAt: "2026-08-09T18:00:00.000Z",
  },
  {
    id: "opp_copper_lobby",
    name: "Copperline lobby refresh",
    clientId: "cli_copperline",
    primaryContactId: "con_copper_helen",
    stage: "pursuing",
    value: 86000,
    bidDueAt: "2026-09-18",
    preBidWalkAt: "2026-09-08",
    location: "299 Milwaukee St, Denver, CO",
    projectType: "tenant_improvement",
    deliveryMethod: "gc_mp",
    estimator: "Jordan Hale",
    ownerStaffId: "staff_jordan",
    winProbability: 15,
    nextStep: "Helen will bid it if we can work nights. Not the core book.",
    createdAt: "2026-08-13T17:30:00.000Z",
  },
  {
    id: "opp_lost_roof",
    name: "Calder Louisville roof",
    clientId: null,
    primaryContactId: "con_wes",
    stage: "lost",
    value: 19600,
    bidDueAt: "2026-07-30",
    preBidWalkAt: "2026-07-22",
    location: "1012 Grant Ave, Louisville, CO",
    projectType: "roofing",
    deliveryMethod: "insurance_claim",
    estimator: "Priya Shah",
    ownerStaffId: "staff_priya",
    winProbability: 0,
    nextStep: "Lost to a storm chaser. Debrief with Wes before the next hail cycle.",
    lostReason: "Homeowner took the cheaper storm-chaser number. No supplement path.",
    createdAt: "2026-07-16T15:00:00.000Z",
  },
  {
    id: "opp_lost_siding",
    name: "Voss siding — Centennial (lost)",
    clientId: null,
    primaryContactId: "con_max",
    stage: "lost",
    value: 27400,
    bidDueAt: "2026-06-12",
    preBidWalkAt: "2026-06-04",
    location: "6980 S Holly St, Centennial, CO",
    projectType: "exterior",
    deliveryMethod: "fixed_price",
    estimator: "Priya Shah",
    ownerStaffId: "staff_priya",
    winProbability: 0,
    nextStep: "Lost on start date. He is back for windows.",
    lostReason: "Could not start before school. He kept us for the window package.",
    createdAt: "2026-05-28T16:20:00.000Z",
  },
];

export const extraJobs: JobDraft[] = [
  {
    id: "job_alvarez_roof",
    opportunityId: "opp_alvarez_roof",
    name: "Alvarez hail roof",
    clientId: null,
    primaryContactId: "con_dana",
    status: "in_progress",
    contractValue: 28400,
    startDate: "2026-07-28",
    substantialCompletion: "2026-08-22",
    superintendent: "Tom Brennan",
    projectManager: "Elena Voss",
    location: "2841 Forest St, Denver, CO",
    ownerStaffId: "staff_elena",
  },
  {
    id: "job_hart_water",
    opportunityId: "opp_hart_water",
    name: "Hart water restoration",
    clientId: null,
    primaryContactId: "con_owen",
    status: "in_progress",
    contractValue: 41200,
    startDate: "2026-07-02",
    substantialCompletion: "2026-09-12",
    superintendent: "Tom Brennan",
    projectManager: "Elena Voss",
    location: "3428 Osceola St, Denver, CO",
    ownerStaffId: "staff_elena",
  },
  {
    id: "job_solano_fire",
    opportunityId: "opp_solano_fire",
    name: "Solano fire restoration",
    clientId: null,
    primaryContactId: "con_mira",
    status: "precon",
    contractValue: 186000,
    startDate: "2026-10-06",
    substantialCompletion: "2027-03-20",
    superintendent: "Tom Brennan",
    projectManager: "Maya Chen",
    location: "12844 E 13th Ave, Aurora, CO",
    ownerStaffId: "staff_maya",
  },
  {
    id: "job_whitfield_bsmt",
    opportunityId: "opp_whitfield_bsmt",
    name: "Whitfield basement finish",
    clientId: null,
    primaryContactId: "con_ben",
    status: "in_progress",
    contractValue: 64000,
    startDate: "2026-06-02",
    substantialCompletion: "2026-10-16",
    superintendent: "Tom Brennan",
    projectManager: "Elena Voss",
    location: "860 S University Blvd, Denver, CO",
    ownerStaffId: "staff_elena",
  },
  {
    id: "job_calder_siding",
    opportunityId: "opp_calder_siding",
    name: "Calder siding & trim",
    clientId: null,
    primaryContactId: "con_ivy",
    status: "punch",
    contractValue: 31800,
    startDate: "2026-05-11",
    substantialCompletion: "2026-08-14",
    superintendent: "Tom Brennan",
    projectManager: "Luis Ortega",
    location: "1844 Grove St, Boulder, CO",
    ownerStaffId: "staff_luis",
  },
  {
    id: "job_patel_roof",
    opportunityId: "opp_patel_roof",
    name: "Patel roof replacement",
    clientId: null,
    primaryContactId: "con_ross",
    status: "complete",
    contractValue: 19200,
    startDate: "2026-03-23",
    substantialCompletion: "2026-04-04",
    superintendent: "Tom Brennan",
    projectManager: "Luis Ortega",
    location: "8124 E 29th Ave, Denver, CO",
    ownerStaffId: "staff_luis",
  },
  {
    id: "job_blake_kitchen",
    opportunityId: "opp_blake_kitchen",
    name: "Blake kitchen remodel",
    clientId: null,
    primaryContactId: "con_nora",
    status: "in_progress",
    contractValue: 54000,
    startDate: "2026-06-23",
    substantialCompletion: "2026-09-25",
    superintendent: "Tom Brennan",
    projectManager: "Maya Chen",
    location: "1374 Madison St, Denver, CO",
    ownerStaffId: "staff_maya",
  },
  {
    id: "job_nguyen_windows",
    opportunityId: "opp_nguyen_windows",
    name: "Nguyen window package",
    clientId: null,
    primaryContactId: "con_cara",
    status: "complete",
    contractValue: 22100,
    startDate: "2026-03-09",
    substantialCompletion: "2026-03-28",
    superintendent: "Tom Brennan",
    projectManager: "Elena Voss",
    location: "430 W 2nd Ave, Denver, CO",
    ownerStaffId: "staff_elena",
  },
  {
    id: "job_ortiz_hail",
    opportunityId: "opp_ortiz_hail",
    name: "Ortiz hail roof",
    clientId: null,
    primaryContactId: "con_sam_ortiz",
    status: "on_hold",
    contractValue: 16800,
    startDate: "2026-08-24",
    substantialCompletion: "2026-09-12",
    superintendent: "Tom Brennan",
    projectManager: "Luis Ortega",
    location: "3227 Larimer St, Denver, CO",
    ownerStaffId: "staff_luis",
  },
  {
    id: "job_redmond_add",
    opportunityId: "opp_redmond_add",
    name: "Redmond rear addition",
    clientId: null,
    primaryContactId: "con_cleo",
    status: "precon",
    contractValue: 148000,
    startDate: "2026-09-08",
    substantialCompletion: "2027-02-27",
    superintendent: "Tom Brennan",
    projectManager: "Maya Chen",
    location: "255 Steele St, Denver, CO",
    ownerStaffId: "staff_maya",
  },
  {
    id: "job_nash_deck",
    opportunityId: "opp_nash_deck",
    name: "Nash deck rebuild",
    clientId: null,
    primaryContactId: "con_greg",
    status: "complete",
    contractValue: 24600,
    startDate: "2026-04-13",
    substantialCompletion: "2026-05-16",
    superintendent: "Tom Brennan",
    projectManager: "Luis Ortega",
    location: "710 10th St, Golden, CO",
    ownerStaffId: "staff_luis",
  },
  {
    id: "job_copper_200",
    opportunityId: null,
    name: "Copperline — Suite 200 TI",
    clientId: "cli_copperline",
    primaryContactId: "con_copper_helen",
    status: "complete",
    contractValue: 186000,
    startDate: "2025-11-03",
    substantialCompletion: "2026-04-17",
    superintendent: "Tom Brennan",
    projectManager: "Elena Voss",
    location: "299 Milwaukee St, Denver, CO",
    ownerStaffId: "staff_elena",
  },
];

export const extraActivities: Activity[] = [
  {
    id: "act_r1",
    entityType: "opportunity",
    entityId: "opp_ellison_kit",
    type: "site_walk",
    body: "Walked Wash Park kitchen with Marcus and Brook. Load-bearing wall at the pantry — need an engineer letter before we price the island.",
    createdAt: "2026-08-19T16:40:00.000Z",
    author: "Elena Voss",
  },
  {
    id: "act_r2",
    entityType: "job",
    entityId: "job_alvarez_roof",
    type: "note",
    body: "Tear-off complete on the south slope. Ice-and-water in the valleys. Dana is out of town until Friday — text photos to her.",
    createdAt: "2026-08-18T21:00:00.000Z",
    author: "Tom Brennan",
  },
  {
    id: "act_r3",
    entityType: "job",
    entityId: "job_hart_water",
    type: "call",
    body: "Nina released the rebuild. Kitchen cabinets are a total loss — opening a second estimate for millwork.",
    createdAt: "2026-08-18T15:20:00.000Z",
    author: "Elena Voss",
  },
  {
    id: "act_r4",
    entityType: "opportunity",
    entityId: "opp_marsh_bath",
    type: "email",
    body: "Sent the LoHi bath proposal. Tile allowance is $14/sf. Theo asked if we can start on a Friday.",
    createdAt: "2026-08-17T19:10:00.000Z",
    author: "Maya Chen",
  },
  {
    id: "act_r5",
    entityType: "job",
    entityId: "job_blake_kitchen",
    type: "note",
    body: "Cabinets delayed two days. Nora knows. Temporary kitchen stays in the dining room.",
    createdAt: "2026-08-17T14:00:00.000Z",
    author: "Maya Chen",
  },
  {
    id: "act_r6",
    entityType: "opportunity",
    entityId: "opp_pell_roof",
    type: "call",
    body: "Al wants a supplement on two skylights. Drew is waiting on us before he signs.",
    createdAt: "2026-08-16T18:30:00.000Z",
    author: "Priya Shah",
  },
  {
    id: "act_r7",
    entityType: "job",
    entityId: "job_calder_siding",
    type: "site_walk",
    body: "Punch with Ivy. North elevation caulk and two window wraps. She asked about replacing the west windows while we are here.",
    createdAt: "2026-08-15T17:00:00.000Z",
    author: "Luis Ortega",
  },
  {
    id: "act_r8",
    entityType: "opportunity",
    entityId: "opp_park_kitchen",
    type: "meeting",
    body: "Joy wants the last three kitchen closeouts, not a capability deck. Send Blake photos and the Congress Park schedule.",
    createdAt: "2026-08-14T16:15:00.000Z",
    author: "Maya Chen",
  },
  {
    id: "act_r9",
    entityType: "job",
    entityId: "job_ortiz_hail",
    type: "note",
    body: "Carrier bounced the supplement. Job on hold. Sam is staying in the unit — do not stage materials.",
    createdAt: "2026-08-13T20:00:00.000Z",
    author: "Luis Ortega",
  },
  {
    id: "act_r10",
    entityType: "opportunity",
    entityId: "opp_lost_roof",
    type: "call",
    body: "Wes went with the cheaper storm chaser. Told him we will still walk the next claim if the work fails.",
    createdAt: "2026-08-01T15:40:00.000Z",
    author: "Priya Shah",
  },
  {
    id: "act_r11",
    entityType: "job",
    entityId: "job_whitfield_bsmt",
    type: "meeting",
    body: "Mechanical rough scheduled. Ben asked about starting the kitchen the day we punch the basement.",
    createdAt: "2026-08-12T14:50:00.000Z",
    author: "Elena Voss",
  },
  {
    id: "act_r12",
    entityType: "opportunity",
    entityId: "opp_solano_fire",
    type: "site_walk",
    body: "Fire restoration walk with Mira and the adjuster. Structure is sound. Contents pack-out is owner-arranged.",
    createdAt: "2026-08-04T16:00:00.000Z",
    author: "Maya Chen",
  },
];

export const extraTasks: Task[] = [
  {
    id: "tsk_r1",
    title: "Engineer letter for Ellison pantry wall",
    dueAt: "2026-08-21",
    completed: false,
    relatedType: "opportunity",
    relatedId: "opp_ellison_kit",
    assignee: "Elena Voss",
  },
  {
    id: "tsk_r2",
    title: "Alvarez south-slope photos to Dana",
    dueAt: "2026-08-20",
    completed: false,
    relatedType: "job",
    relatedId: "job_alvarez_roof",
    assignee: "Tom Brennan",
  },
  {
    id: "tsk_r3",
    title: "Hart millwork list from Nina",
    dueAt: "2026-08-21",
    completed: false,
    relatedType: "opportunity",
    relatedId: "opp_hart_rebuild",
    assignee: "Elena Voss",
  },
  {
    id: "tsk_r4",
    title: "Follow Theo on the bath proposal",
    dueAt: "2026-08-22",
    completed: false,
    relatedType: "opportunity",
    relatedId: "opp_marsh_bath",
    assignee: "Maya Chen",
  },
  {
    id: "tsk_r5",
    title: "Blake cabinet delivery — Thursday",
    dueAt: "2026-08-21",
    completed: false,
    relatedType: "job",
    relatedId: "job_blake_kitchen",
    assignee: "Maya Chen",
  },
  {
    id: "tsk_r6",
    title: "Pell skylight supplement to Al",
    dueAt: "2026-08-22",
    completed: false,
    relatedType: "opportunity",
    relatedId: "opp_pell_roof",
    assignee: "Priya Shah",
  },
  {
    id: "tsk_r7",
    title: "Calder west-window price",
    dueAt: "2026-08-23",
    completed: false,
    relatedType: "opportunity",
    relatedId: "opp_calder_win",
    assignee: "Luis Ortega",
  },
  {
    id: "tsk_r8",
    title: "Send Joy the Blake kitchen photos",
    dueAt: "2026-08-20",
    completed: false,
    relatedType: "opportunity",
    relatedId: "opp_park_kitchen",
    assignee: "Maya Chen",
  },
  {
    id: "tsk_r9",
    title: "Brooks HOA walk — Wednesday",
    dueAt: "2026-08-26",
    completed: false,
    relatedType: "opportunity",
    relatedId: "opp_brooks_ext",
    assignee: "Priya Shah",
  },
  {
    id: "tsk_r10",
    title: "Redmond permit set with Hale + Moss",
    dueAt: "2026-08-27",
    completed: false,
    relatedType: "job",
    relatedId: "job_redmond_add",
    assignee: "Maya Chen",
  },
  {
    id: "tsk_r11",
    title: "Ortiz carrier follow-up",
    dueAt: "2026-08-25",
    completed: false,
    relatedType: "job",
    relatedId: "job_ortiz_hail",
    assignee: "Luis Ortega",
  },
  {
    id: "tsk_r12",
    title: "Whitfield kitchen proposal follow-up",
    dueAt: "2026-08-24",
    completed: false,
    relatedType: "opportunity",
    relatedId: "opp_whitfield_kit",
    assignee: "Elena Voss",
  },
];
