import type { Activity, Client, Contact, Job, Opportunity, Task } from "@/lib/types";

export const extraClients: Client[] = [
  {
    id: "cli_redstone",
    name: "Redstone Development",
    type: "developer",
    city: "Boulder",
    state: "CO",
    notes:
      "Infill mixed-use along Pearl and 30th. They shortlist three GCs and award on schedule plus fee. Bonding not an issue.",
  },
  {
    id: "cli_larimer",
    name: "Larimer Associates",
    type: "developer",
    city: "Denver",
    state: "CO",
    notes: "LoDo and RiNo apartment owner. Repeat TI and amenity renovations. Payment is 30 days once draw is certified.",
  },
  {
    id: "cli_childrens",
    name: "Children's Hospital Colorado",
    type: "healthcare_system",
    city: "Aurora",
    state: "CO",
    notes: "Anschutz campus. ICRA, after-hours, and infection-control walkthroughs on every package. Prefers known GCs.",
  },
  {
    id: "cli_jeffco",
    name: "Jefferson County",
    type: "public",
    city: "Golden",
    state: "CO",
    notes: "Facilities and libraries. Hard bid, prevailing wage, electronic bid forms. Council award the first Tuesday.",
  },
  {
    id: "cli_uchealth",
    name: "UCHealth",
    type: "healthcare_system",
    city: "Aurora",
    state: "CO",
    notes: "Centralized facilities. Design-assist on OR and imaging. Insurance limits are high; confirm before pursuing.",
  },
  {
    id: "cli_dha",
    name: "Denver Housing Authority",
    type: "public",
    city: "Denver",
    state: "CO",
    notes: "Section 3 and Davis-Bacon on most work. Occupied rehab. Community meetings before award.",
  },
  {
    id: "cli_sage",
    name: "Sage Hospitality",
    type: "owner",
    city: "Denver",
    state: "CO",
    notes: "Hotel renovations while open. Night work and quiet hours. Brand standards drive millwork and FF&E.",
  },
  {
    id: "cli_continuum",
    name: "Continuum Partners",
    type: "developer",
    city: "Denver",
    state: "CO",
    notes: "Large mixed-use. CM-at-risk with open book. They want a precon team that can hold a GMP.",
  },
  {
    id: "cli_ktgy",
    name: "KTGY Architecture",
    type: "architect",
    city: "Denver",
    state: "CO",
    notes: "Multifamily specifier. Puts Northline on bid lists when they like the last job’s closeout.",
  },
  {
    id: "cli_flatiron",
    name: "Flatiron Roasting Co.",
    type: "owner",
    city: "Louisville",
    state: "CO",
    notes: "Owner-builder of a roasting plant and tasting room. Design-build. Decision is the founder plus their GC cousin.",
  },
];

export const extraContacts: Contact[] = [
  {
    id: "con_redstone_cleo",
    clientId: "cli_redstone",
    name: "Cleo Hart",
    title: "Development manager",
    email: "cleo@redstonedev.com",
    phone: "(303) 555-4410",
    ownerStaffId: "staff_priya",
    isReferralPartner: false,
  },
  {
    id: "con_redstone_ben",
    clientId: "cli_redstone",
    name: "Ben Ibarra",
    title: "Principal",
    email: "ben@redstonedev.com",
    phone: "(303) 555-4411",
    ownerStaffId: "staff_priya",
    isReferralPartner: true,
  },
  {
    id: "con_larimer_joy",
    clientId: "cli_larimer",
    name: "Joy Kessler",
    title: "Director of Construction",
    email: "joy@larimerassoc.com",
    phone: "(303) 555-2288",
    ownerStaffId: "staff_elena",
    isReferralPartner: false,
  },
  {
    id: "con_larimer_owen",
    clientId: "cli_larimer",
    name: "Owen Blake",
    title: "Asset manager",
    email: "owen@larimerassoc.com",
    phone: "(303) 555-2290",
    ownerStaffId: "staff_elena",
    isReferralPartner: false,
  },
  {
    id: "con_child_mira",
    clientId: "cli_childrens",
    name: "Mira Solano",
    title: "Project manager, Facilities",
    email: "mira.solano@childrenscolorado.org",
    phone: "(720) 555-6701",
    ownerStaffId: "staff_maya",
    isReferralPartner: false,
  },
  {
    id: "con_child_greg",
    clientId: "cli_childrens",
    name: "Greg Holtz",
    title: "Director of Planning",
    email: "greg.holtz@childrenscolorado.org",
    phone: "(720) 555-6704",
    ownerStaffId: "staff_maya",
    isReferralPartner: false,
  },
  {
    id: "con_jeffco_al",
    clientId: "cli_jeffco",
    name: "Al Yoon",
    title: "Capital projects supervisor",
    email: "ayoon@jeffco.us",
    phone: "(303) 555-8802",
    ownerStaffId: "staff_luis",
    isReferralPartner: false,
  },
  {
    id: "con_uc_nina",
    clientId: "cli_uchealth",
    name: "Nina Pruitt",
    title: "Construction services",
    email: "nina.pruitt@uchealth.org",
    phone: "(720) 555-3109",
    ownerStaffId: "staff_maya",
    isReferralPartner: false,
  },
  {
    id: "con_dha_isa",
    clientId: "cli_dha",
    name: "Isa Morales",
    title: "Senior project manager",
    email: "isa.morales@denverhousing.org",
    phone: "(720) 555-9901",
    ownerStaffId: "staff_luis",
    isReferralPartner: false,
  },
  {
    id: "con_sage_theo",
    clientId: "cli_sage",
    name: "Theo Lang",
    title: "VP, Design & Construction",
    email: "theo.lang@sagehospitality.com",
    phone: "(303) 555-1506",
    ownerStaffId: "staff_jordan",
    isReferralPartner: false,
  },
  {
    id: "con_cont_lina",
    clientId: "cli_continuum",
    name: "Lina Okada",
    title: "Development director",
    email: "lina.okada@continuumpartners.com",
    phone: "(303) 555-7744",
    ownerStaffId: "staff_priya",
    isReferralPartner: true,
  },
  {
    id: "con_ktgy_ross",
    clientId: "cli_ktgy",
    name: "Ross Pell",
    title: "Principal",
    email: "rpell@ktgy.com",
    phone: "(303) 555-6120",
    ownerStaffId: "staff_priya",
    isReferralPartner: true,
  },
  {
    id: "con_flat_ivy",
    clientId: "cli_flatiron",
    name: "Ivy Marsh",
    title: "Founder",
    email: "ivy@flatironroast.com",
    phone: "(720) 555-4040",
    ownerStaffId: "staff_maya",
    isReferralPartner: false,
  },
  {
    id: "con_meridian_drew",
    clientId: "cli_meridian",
    name: "Drew Sable",
    title: "Project accountant",
    email: "drew.sable@meridianprop.com",
    phone: "(303) 555-0148",
    ownerStaffId: "staff_elena",
    isReferralPartner: false,
  },
  {
    id: "con_luke_cara",
    clientId: "cli_luke",
    name: "Cara Nguyen",
    title: "ICRA coordinator",
    email: "cnguyen@stlukes.org",
    phone: "(720) 555-2224",
    ownerStaffId: "staff_maya",
    isReferralPartner: false,
  },
  {
    id: "con_copper_max",
    clientId: "cli_copperline",
    name: "Max Rhee",
    title: "Tenant coordinator",
    email: "max@copperline.com",
    phone: "(303) 555-0918",
    ownerStaffId: "staff_jordan",
    isReferralPartner: false,
  },
];

export const extraOpportunities: Opportunity[] = [
  {
    id: "opp_pearl",
    name: "Pearl Street Mixed-Use",
    clientId: "cli_redstone",
    primaryContactId: "con_redstone_cleo",
    stage: "estimating",
    value: 38400000,
    bidDueAt: "2026-09-16",
    preBidWalkAt: "2026-08-28",
    location: "Pearl Street, Boulder, CO",
    projectType: "multifamily",
    deliveryMethod: "cm_at_risk",
    estimator: "Priya Shah",
    ownerStaffId: "staff_priya",
    winProbability: 30,
    nextStep: "Price Type V over podium. Confirm Boulder energy code path.",
    createdAt: "2026-07-08T16:00:00.000Z",
  },
  {
    id: "opp_lohi",
    name: "LoHi Commons Phase 2",
    clientId: "cli_larimer",
    primaryContactId: "con_larimer_joy",
    stage: "interview",
    value: 29100000,
    bidDueAt: "2026-09-09",
    preBidWalkAt: "2026-08-21",
    location: "LoHi, Denver, CO",
    projectType: "multifamily",
    deliveryMethod: "cm_at_risk",
    estimator: "Maya Chen",
    ownerStaffId: "staff_maya",
    winProbability: 65,
    nextStep: "Staffing chart and last three closeout scores. Joy wants names, not a brochure.",
    createdAt: "2026-06-20T15:30:00.000Z",
  },
  {
    id: "opp_or4",
    name: "Children's OR Suite 4 Build-out",
    clientId: "cli_childrens",
    primaryContactId: "con_child_mira",
    stage: "bid_submitted",
    value: 9600000,
    bidDueAt: "2026-08-26",
    preBidWalkAt: "2026-08-12",
    location: "Anschutz, Aurora, CO",
    projectType: "healthcare",
    deliveryMethod: "cm_at_risk",
    estimator: "Maya Chen",
    ownerStaffId: "staff_maya",
    winProbability: 45,
    nextStep: "ICRA plan and after-hours logistics memo to Mira by Friday.",
    createdAt: "2026-06-02T14:00:00.000Z",
  },
  {
    id: "opp_golden_lib",
    name: "Golden Library Addition",
    clientId: "cli_jeffco",
    primaryContactId: "con_jeffco_al",
    stage: "pursuing",
    value: 7400000,
    bidDueAt: "2026-10-08",
    preBidWalkAt: "2026-09-15",
    location: "Golden, CO",
    projectType: "civic",
    deliveryMethod: "design_bid_build",
    estimator: "Priya Shah",
    ownerStaffId: "staff_priya",
    winProbability: 15,
    nextStep: "Register on BidNet. Hale + Moss is design. Pull soils report.",
    createdAt: "2026-08-16T17:00:00.000Z",
  },
  {
    id: "opp_uc_lab",
    name: "UCHealth Central Lab Fit-out",
    clientId: "cli_uchealth",
    primaryContactId: "con_uc_nina",
    stage: "estimating",
    value: 12800000,
    bidDueAt: "2026-09-22",
    preBidWalkAt: "2026-09-03",
    location: "Anschutz, Aurora, CO",
    projectType: "healthcare",
    deliveryMethod: "design_build",
    estimator: "Maya Chen",
    ownerStaffId: "staff_maya",
    winProbability: 30,
    nextStep: "Vibration criteria for analyzers. Get MEP design-assist fee.",
    createdAt: "2026-07-28T18:10:00.000Z",
  },
  {
    id: "opp_sun_valley",
    name: "Sun Valley Homes Rehab — 48 units",
    clientId: "cli_dha",
    primaryContactId: "con_dha_isa",
    stage: "pursuing",
    value: 11200000,
    bidDueAt: "2026-10-14",
    preBidWalkAt: "2026-09-22",
    location: "Sun Valley, Denver, CO",
    projectType: "multifamily",
    deliveryMethod: "design_bid_build",
    estimator: "Luis Ortega",
    ownerStaffId: "staff_luis",
    winProbability: 15,
    nextStep: "Section 3 plan and occupied-rehab logistics. Walk units with Isa.",
    createdAt: "2026-08-10T16:40:00.000Z",
  },
  {
    id: "opp_oxford",
    name: "Oxford Hotel Guestroom Refresh",
    clientId: "cli_sage",
    primaryContactId: "con_sage_theo",
    stage: "interview",
    value: 4300000,
    bidDueAt: "2026-08-27",
    preBidWalkAt: null,
    location: "LoDo, Denver, CO",
    projectType: "hospitality",
    deliveryMethod: "gc_mp",
    estimator: "Jordan Hale",
    ownerStaffId: "staff_jordan",
    winProbability: 70,
    nextStep: "Night-work staffing and quiet-hours plan. Brand FF&E is owner-furnished.",
    createdAt: "2026-07-18T19:20:00.000Z",
  },
  {
    id: "opp_union",
    name: "Union Station Tower Podium",
    clientId: "cli_continuum",
    primaryContactId: "con_cont_lina",
    stage: "pursuing",
    value: 86000000,
    bidDueAt: "2026-11-06",
    preBidWalkAt: "2026-10-08",
    location: "Union Station, Denver, CO",
    projectType: "commercial",
    deliveryMethod: "cm_at_risk",
    estimator: "Priya Shah",
    ownerStaffId: "staff_priya",
    winProbability: 15,
    nextStep: "Qualify bonding capacity and a precon fee. Lina wants a letter this week.",
    createdAt: "2026-08-04T15:00:00.000Z",
  },
  {
    id: "opp_roast",
    name: "Flatiron Roastery & Tasting Room",
    clientId: "cli_flatiron",
    primaryContactId: "con_flat_ivy",
    stage: "bid_submitted",
    value: 3800000,
    bidDueAt: "2026-08-25",
    preBidWalkAt: "2026-08-11",
    location: "Louisville, CO",
    projectType: "industrial",
    deliveryMethod: "design_build",
    estimator: "Maya Chen",
    ownerStaffId: "staff_maya",
    winProbability: 45,
    nextStep: "Roaster pad loads and grease exhaust. Ivy wants a GMP she can take to the bank.",
    createdAt: "2026-07-02T14:30:00.000Z",
  },
  {
    id: "opp_ktgy_list",
    name: "RiNo Five — bid list (KTGY)",
    clientId: "cli_ktgy",
    primaryContactId: "con_ktgy_ross",
    stage: "pursuing",
    value: 52000000,
    bidDueAt: "2026-10-20",
    preBidWalkAt: "2026-09-29",
    location: "RiNo, Denver, CO",
    projectType: "multifamily",
    deliveryMethod: "cm_at_risk",
    estimator: "Priya Shah",
    ownerStaffId: "staff_priya",
    winProbability: 15,
    nextStep: "Ross will put us on the list if we send last year’s RiNo closeout photos.",
    createdAt: "2026-08-17T18:00:00.000Z",
  },
  {
    id: "opp_dps_gym",
    name: "DPS East High Gym Floor Replacement",
    clientId: "cli_dps",
    primaryContactId: "con_dps_marisol",
    stage: "lost",
    value: 2100000,
    bidDueAt: "2026-07-22",
    preBidWalkAt: "2026-07-08",
    location: "City Park, Denver, CO",
    projectType: "education",
    deliveryMethod: "design_bid_build",
    estimator: "Luis Ortega",
    ownerStaffId: "staff_luis",
    winProbability: 0,
    nextStep: "Lost on summer-window staffing. Debrief with Marisol before the next athletic bid.",
    lostReason: "Could not hold a six-week summer-only crew at their number.",
    createdAt: "2026-06-01T16:00:00.000Z",
  },
  {
    id: "opp_luke_ti",
    name: "St. Luke's Outpatient TI — 3rd floor",
    clientId: "cli_luke",
    primaryContactId: "con_luke_renee",
    stage: "pursuing",
    value: 5400000,
    bidDueAt: "2026-10-28",
    preBidWalkAt: null,
    location: "Highlands, Denver, CO",
    projectType: "tenant_improvement",
    deliveryMethod: "gc_mp",
    estimator: "Maya Chen",
    ownerStaffId: "staff_maya",
    winProbability: 15,
    nextStep: "Renee said Q1. Keep it warm after imaging award.",
    createdAt: "2026-08-12T17:20:00.000Z",
  },
];

export const extraJobs: Job[] = [
  {
    id: "job_oxford",
    opportunityId: null,
    name: "Crawford Hotel Corridor Refresh",
    clientId: "cli_sage",
    status: "in_progress",
    contractValue: 2800000,
    startDate: "2026-05-18",
    substantialCompletion: "2026-10-02",
    superintendent: "Tom Brennan",
    projectManager: "Elena Voss",
    location: "Union Station, Denver, CO",
    ownerStaffId: "staff_elena",
  },
  {
    id: "job_larimer_am",
    opportunityId: null,
    name: "The Confluence Amenity Renovation",
    clientId: "cli_larimer",
    status: "in_progress",
    contractValue: 4100000,
    startDate: "2026-04-06",
    substantialCompletion: "2026-11-20",
    superintendent: "Tom Brennan",
    projectManager: "Elena Voss",
    location: "RiNo, Denver, CO",
    ownerStaffId: "staff_elena",
  },
  {
    id: "job_jeffco_yard",
    opportunityId: null,
    name: "Jeffco Fleet Maintenance Shop",
    clientId: "cli_jeffco",
    status: "punch",
    contractValue: 6700000,
    startDate: "2025-03-10",
    substantialCompletion: "2026-08-07",
    superintendent: "Tom Brennan",
    projectManager: "Luis Ortega",
    location: "Golden, CO",
    ownerStaffId: "staff_luis",
  },
  {
    id: "job_dha_osage",
    opportunityId: null,
    name: "Osage Scattered Sites Envelope",
    clientId: "cli_dha",
    status: "complete",
    contractValue: 3900000,
    startDate: "2025-04-14",
    substantialCompletion: "2026-03-28",
    superintendent: "Tom Brennan",
    projectManager: "Luis Ortega",
    location: "West Denver, CO",
    ownerStaffId: "staff_luis",
  },
  {
    id: "job_child_infill",
    opportunityId: null,
    name: "Children's Infusion Center Infill",
    clientId: "cli_childrens",
    status: "precon",
    contractValue: 7200000,
    startDate: "2026-10-12",
    substantialCompletion: "2027-06-30",
    superintendent: "Tom Brennan",
    projectManager: "Elena Voss",
    location: "Anschutz, Aurora, CO",
    ownerStaffId: "staff_elena",
  },
  {
    id: "job_flatiron",
    opportunityId: "opp_roast",
    name: "Flatiron Roastery — early buyout",
    clientId: "cli_flatiron",
    status: "on_hold",
    contractValue: 3800000,
    startDate: "2026-09-14",
    substantialCompletion: "2027-03-01",
    superintendent: "Tom Brennan",
    projectManager: "Luis Ortega",
    location: "Louisville, CO",
    ownerStaffId: "staff_luis",
  },
  {
    id: "job_copper_200",
    opportunityId: null,
    name: "Copperline — Suite 200 TI",
    clientId: "cli_copperline",
    status: "complete",
    contractValue: 1650000,
    startDate: "2025-11-03",
    substantialCompletion: "2026-04-17",
    superintendent: "Tom Brennan",
    projectManager: "Elena Voss",
    location: "Cherry Creek, Denver, CO",
    ownerStaffId: "staff_elena",
  },
];

export const extraActivities: Activity[] = [
  {
    id: "act_11",
    entityType: "opportunity",
    entityId: "opp_or4",
    type: "email",
    body: "Submitted OR 4 GMP with ICRA matrix and after-hours manpower histogram. Mira asked for a weekend-only demo window.",
    createdAt: "2026-08-19T20:15:00.000Z",
    author: "Maya Chen",
  },
  {
    id: "act_12",
    entityType: "opportunity",
    entityId: "opp_lohi",
    type: "meeting",
    body: "Interview with Joy. She wants superintendent names and three references from occupied rehabs, not just new buildings.",
    createdAt: "2026-08-18T18:00:00.000Z",
    author: "Elena Voss",
  },
  {
    id: "act_13",
    entityType: "job",
    entityId: "job_oxford",
    type: "note",
    body: "Night shift hit 6 rooms. Brand millwork for floors 4–5 is two weeks late. Theo knows; we are skipping those floors.",
    createdAt: "2026-08-18T11:40:00.000Z",
    author: "Elena Voss",
  },
  {
    id: "act_14",
    entityType: "opportunity",
    entityId: "opp_union",
    type: "call",
    body: "Lina asked for a bonding letter at $90M and a precon fee proposal. She is talking to two other CMs.",
    createdAt: "2026-08-17T16:22:00.000Z",
    author: "Priya Shah",
  },
  {
    id: "act_15",
    entityType: "job",
    entityId: "job_jeffco_yard",
    type: "site_walk",
    body: "Punch at 22 items. Fleet manager wants the wash bay epoxy before they move trucks back in.",
    createdAt: "2026-08-15T19:00:00.000Z",
    author: "Luis Ortega",
  },
  {
    id: "act_16",
    entityType: "opportunity",
    entityId: "opp_pearl",
    type: "note",
    body: "Boulder energy code path is still ambiguous. Estimating both all-electric and hybrid HVAC until Cleo decides.",
    createdAt: "2026-08-14T21:10:00.000Z",
    author: "Priya Shah",
  },
  {
    id: "act_17",
    entityType: "client",
    entityId: "cli_childrens",
    type: "meeting",
    body: "Quarterly with Greg. Infusion center is funded. OR 4 is the near-term award. They will not bid to new GCs.",
    createdAt: "2026-08-11T17:30:00.000Z",
    author: "Jordan Hale",
  },
  {
    id: "act_18",
    entityType: "opportunity",
    entityId: "opp_oxford",
    type: "call",
    body: "Theo wants a 12-room-per-week clip with the hotel open. Quiet hours 10 p.m. to 7 a.m. except floors we own.",
    createdAt: "2026-08-19T15:05:00.000Z",
    author: "Jordan Hale",
  },
  {
    id: "act_19",
    entityType: "job",
    entityId: "job_larimer_am",
    type: "note",
    body: "Pool plaster is next week. Occupied building — isolation at the amenity level is holding.",
    createdAt: "2026-08-13T14:50:00.000Z",
    author: "Tom Brennan",
  },
  {
    id: "act_20",
    entityType: "opportunity",
    entityId: "opp_dps_gym",
    type: "stage_change",
    body: "Lost. Could not staff a six-week summer window at their number. Marisol still wants us on the next CTE bid.",
    createdAt: "2026-07-24T18:00:00.000Z",
    author: "Luis Ortega",
  },
  {
    id: "act_21",
    entityType: "job",
    entityId: "job_dha_osage",
    type: "note",
    body: "Closeout binder issued. Warranty walk complete. Isa signed substantial on March 28.",
    createdAt: "2026-04-02T16:00:00.000Z",
    author: "Luis Ortega",
  },
  {
    id: "act_22",
    entityType: "opportunity",
    entityId: "opp_roast",
    type: "site_walk",
    body: "Walked the Louisville shell with Ivy. Roaster pad is the long lead. She wants a GMP she can take to FirstBank.",
    createdAt: "2026-08-11T20:00:00.000Z",
    author: "Maya Chen",
  },
];

export const extraTasks: Task[] = [
  {
    id: "tsk_9",
    title: "ICRA memo for Children's OR 4",
    dueAt: "2026-08-22",
    completed: false,
    relatedType: "opportunity",
    relatedId: "opp_or4",
    assignee: "Maya Chen",
  },
  {
    id: "tsk_10",
    title: "Bonding letter — Union Station Tower",
    dueAt: "2026-08-22",
    completed: false,
    relatedType: "opportunity",
    relatedId: "opp_union",
    assignee: "Priya Shah",
  },
  {
    id: "tsk_11",
    title: "Oxford quiet-hours staffing plan",
    dueAt: "2026-08-21",
    completed: false,
    relatedType: "opportunity",
    relatedId: "opp_oxford",
    assignee: "Jordan Hale",
  },
  {
    id: "tsk_12",
    title: "Jeffco wash bay epoxy punch",
    dueAt: "2026-08-25",
    completed: false,
    relatedType: "job",
    relatedId: "job_jeffco_yard",
    assignee: "Luis Ortega",
  },
  {
    id: "tsk_13",
    title: "LoHi Commons references for Joy",
    dueAt: "2026-08-24",
    completed: false,
    relatedType: "opportunity",
    relatedId: "opp_lohi",
    assignee: "Elena Voss",
  },
  {
    id: "tsk_14",
    title: "Pearl Street energy-code path",
    dueAt: "2026-08-27",
    completed: false,
    relatedType: "opportunity",
    relatedId: "opp_pearl",
    assignee: "Priya Shah",
  },
  {
    id: "tsk_15",
    title: "Roaster pad loads from manufacturer",
    dueAt: "2026-08-26",
    completed: false,
    relatedType: "opportunity",
    relatedId: "opp_roast",
    assignee: "Maya Chen",
  },
  {
    id: "tsk_16",
    title: "KTGY closeout photos for RiNo Five",
    dueAt: "2026-08-23",
    completed: false,
    relatedType: "opportunity",
    relatedId: "opp_ktgy_list",
    assignee: "Priya Shah",
  },
  {
    id: "tsk_17",
    title: "Crawford millwork delay notice",
    dueAt: "2026-08-20",
    completed: true,
    relatedType: "job",
    relatedId: "job_oxford",
    assignee: "Elena Voss",
  },
  {
    id: "tsk_18",
    title: "Register Golden Library on BidNet",
    dueAt: "2026-08-28",
    completed: false,
    relatedType: "opportunity",
    relatedId: "opp_golden_lib",
    assignee: "Priya Shah",
  },
];
