import { NORTHLINE_STAFF, NORTHLINE_TEAMS, type CrmState } from "@/lib/types";
import { demoOps } from "@/lib/demo-ops";

export const seedState: CrmState = {
  staff: structuredClone(NORTHLINE_STAFF),
  teams: structuredClone(NORTHLINE_TEAMS),
  clients: [
    {
      id: "cli_meridian",
      name: "Meridian Properties",
      type: "developer",
      city: "Denver",
      state: "CO",
      notes:
        "Repeat developer. Prefers CM-at-risk on mixed-use. Decision cycle runs through their construction committee.",
    },
    {
      id: "cli_luke",
      name: "St. Luke's Health System",
      type: "healthcare_system",
      city: "Denver",
      state: "CO",
      notes:
        "IDIQ-style relationship on outpatient work. Strict ICRA and after-hours requirements. Bonding required on every bid.",
    },
    {
      id: "cli_dps",
      name: "Denver Public Schools",
      type: "public",
      city: "Denver",
      state: "CO",
      notes:
        "Hard-bid public work. Prevailing wage. Pre-bid walks are mandatory and they enforce bid form completeness.",
    },
    {
      id: "cli_peakwest",
      name: "Peak West Capital",
      type: "developer",
      city: "Boulder",
      state: "CO",
      notes:
        "Multifamily fund. Fast VE after shortlist. They care more about schedule certainty than lowest number.",
    },
    {
      id: "cli_copperline",
      name: "Copperline Retail Group",
      type: "owner",
      city: "Cherry Creek",
      state: "CO",
      notes: "Retail and hospitality interiors. Often sole-source Northline on TI once design is at 80%.",
    },
    {
      id: "cli_frontrange",
      name: "Front Range Industrial",
      type: "owner",
      city: "Commerce City",
      state: "CO",
      notes: "Owner-operator of cold storage and light industrial. Design-build is their default delivery.",
    },
    {
      id: "cli_aurora",
      name: "City of Aurora",
      type: "public",
      city: "Aurora",
      state: "CO",
      notes: "Facilities and public safety. Council award calendar drives close dates.",
    },
    {
      id: "cli_hale",
      name: "Hale + Moss Architects",
      type: "architect",
      city: "Denver",
      state: "CO",
      notes:
        "Key specifier. They put Northline on the bid list for most of their commercial and civic work.",
    },
  ],
  contacts: [
    {
      id: "con_meridian_ava",
      clientId: "cli_meridian",
      name: "Ava Lindstrom",
      title: "VP of Development",
      email: "ava.lindstrom@meridianprop.com",
      phone: "(303) 555-0142",
      ownerStaffId: "staff_elena",
      isReferralPartner: false,
    },
    {
      id: "con_meridian_nate",
      clientId: "cli_meridian",
      name: "Nate Crowley",
      title: "Owner's Rep",
      email: "nate.crowley@meridianprop.com",
      phone: "(303) 555-0188",
      ownerStaffId: "staff_elena",
      isReferralPartner: true,
    },
    {
      id: "con_meridian_brook",
      clientId: "cli_meridian",
      name: "Brook Ellison",
      title: "Development broker",
      email: "brook@ellisoncre.com",
      phone: "(303) 555-0194",
      ownerStaffId: "staff_elena",
      isReferralPartner: true,
    },
    {
      id: "con_luke_renee",
      clientId: "cli_luke",
      name: "Renee Okonkwo",
      title: "Director of Facilities",
      email: "rokonkwo@stlukes.org",
      phone: "(720) 555-2210",
      ownerStaffId: "staff_maya",
      isReferralPartner: false,
    },
    {
      id: "con_luke_dan",
      clientId: "cli_luke",
      name: "Dan Pfeiffer",
      title: "Project Executive",
      email: "dpfeiffer@stlukes.org",
      phone: "(720) 555-2218",
      ownerStaffId: "staff_maya",
      isReferralPartner: false,
    },
    {
      id: "con_dps_marisol",
      clientId: "cli_dps",
      name: "Marisol Vega",
      title: "Capital Projects Manager",
      email: "mvega@dpsk12.org",
      phone: "(720) 555-4401",
      ownerStaffId: "staff_luis",
      isReferralPartner: false,
    },
    {
      id: "con_peak_jon",
      clientId: "cli_peakwest",
      name: "Jon Park",
      title: "Principal",
      email: "jon@peakwest.capital",
      phone: "(303) 555-7720",
      ownerStaffId: "staff_priya",
      isReferralPartner: true,
    },
    {
      id: "con_copper_helen",
      clientId: "cli_copperline",
      name: "Helen Cho",
      title: "Director of Construction",
      email: "helen@copperline.com",
      phone: "(303) 555-0914",
      ownerStaffId: "staff_jordan",
      isReferralPartner: false,
    },
    {
      id: "con_front_wes",
      clientId: "cli_frontrange",
      name: "Wes Calder",
      title: "Owner",
      email: "wes@frindustrial.com",
      phone: "(720) 555-8333",
      ownerStaffId: "staff_maya",
      isReferralPartner: false,
    },
    {
      id: "con_aurora_kim",
      clientId: "cli_aurora",
      name: "Kimberly Rhodes",
      title: "Facilities Procurement",
      email: "krhodes@auroragov.org",
      phone: "(303) 555-6002",
      ownerStaffId: "staff_luis",
      isReferralPartner: false,
    },
    {
      id: "con_hale_sam",
      clientId: "cli_hale",
      name: "Sam Moss",
      title: "Partner",
      email: "smoss@halemoss.com",
      phone: "(303) 555-3309",
      ownerStaffId: "staff_maya",
      isReferralPartner: true,
    },
    {
      id: "con_dps_pat",
      clientId: "cli_dps",
      name: "Pat Nguyen",
      title: "Owner's representative",
      email: "pnguyen@civicpm.co",
      phone: "(720) 555-4418",
      ownerStaffId: "staff_luis",
      isReferralPartner: true,
    },
  ],
  opportunities: [
    {
      id: "opp_imaging",
      name: "St. Luke's Highlands Imaging Pavilion",
      clientId: "cli_luke",
      primaryContactId: "con_luke_renee",
      stage: "bid_submitted",
      value: 18400000,
      bidDueAt: "2026-08-21",
      preBidWalkAt: "2026-08-07",
      location: "Highlands, Denver, CO",
      projectType: "healthcare",
      deliveryMethod: "cm_at_risk",
      estimator: "Maya Chen",
      ownerStaffId: "staff_maya",
      winProbability: 45,
      nextStep: "Follow up with Renee after bid tab — they want a GMP by Labor Day.",
      createdAt: "2026-06-12T15:00:00.000Z",
    },
    {
      id: "opp_rino",
      name: "River North Apartments",
      clientId: "cli_peakwest",
      primaryContactId: "con_peak_jon",
      stage: "interview",
      value: 42600000,
      bidDueAt: "2026-08-28",
      preBidWalkAt: "2026-08-14",
      location: "RiNo, Denver, CO",
      projectType: "multifamily",
      deliveryMethod: "cm_at_risk",
      estimator: "Priya Shah",
      ownerStaffId: "staff_priya",
      winProbability: 65,
      nextStep: "VE workshop Thursday. Bring wood-frame vs. podium cost delta.",
      createdAt: "2026-05-03T18:20:00.000Z",
    },
    {
      id: "opp_montbello",
      name: "DPS Montbello Elementary Addition",
      clientId: "cli_dps",
      primaryContactId: "con_dps_marisol",
      stage: "estimating",
      value: 11200000,
      bidDueAt: "2026-09-04",
      preBidWalkAt: "2026-08-25",
      location: "Montbello, Denver, CO",
      projectType: "education",
      deliveryMethod: "design_bid_build",
      estimator: "Maya Chen",
      ownerStaffId: "staff_maya",
      winProbability: 30,
      nextStep: "Finish civil takeoff. Confirm phasing around occupied classrooms.",
      createdAt: "2026-07-22T14:10:00.000Z",
    },
    {
      id: "opp_hotel",
      name: "Union Station Hotel Interior Refresh",
      clientId: "cli_copperline",
      primaryContactId: "con_copper_helen",
      stage: "estimating",
      value: 6700000,
      bidDueAt: "2026-09-11",
      preBidWalkAt: "2026-08-27",
      location: "LoDo, Denver, CO",
      projectType: "hospitality",
      deliveryMethod: "gc_mp",
      estimator: "Priya Shah",
      ownerStaffId: "staff_priya",
      winProbability: 30,
      nextStep: "Get millwork lead times from two finish carpenters before pricing.",
      createdAt: "2026-08-01T16:40:00.000Z",
    },
    {
      id: "opp_cold",
      name: "Front Range Cold Storage Expansion",
      clientId: "cli_frontrange",
      primaryContactId: "con_front_wes",
      stage: "pursuing",
      value: 24100000,
      bidDueAt: "2026-09-18",
      preBidWalkAt: "2026-08-20",
      location: "Commerce City, CO",
      projectType: "industrial",
      deliveryMethod: "design_build",
      estimator: "Maya Chen",
      ownerStaffId: "staff_maya",
      winProbability: 15,
      nextStep: "Attend owner walk Wednesday. Confirm freezer panel vendor.",
      createdAt: "2026-08-11T13:00:00.000Z",
    },
    {
      id: "opp_fire",
      name: "Aurora Fire Station 12",
      clientId: "cli_aurora",
      primaryContactId: "con_aurora_kim",
      stage: "pursuing",
      value: 15800000,
      bidDueAt: "2026-10-02",
      preBidWalkAt: "2026-09-08",
      location: "Aurora, CO",
      projectType: "civic",
      deliveryMethod: "design_bid_build",
      estimator: "Priya Shah",
      ownerStaffId: "staff_priya",
      winProbability: 15,
      nextStep: "Pull bid docs when they post. Hale + Moss is the design team.",
      createdAt: "2026-08-15T17:30:00.000Z",
    },
    {
      id: "opp_cherry_ti",
      name: "Cherry Creek Boutique TI — Suite 400",
      clientId: "cli_copperline",
      primaryContactId: "con_copper_helen",
      stage: "interview",
      value: 2100000,
      bidDueAt: "2026-08-22",
      preBidWalkAt: null,
      location: "Cherry Creek, Denver, CO",
      projectType: "tenant_improvement",
      deliveryMethod: "gc_mp",
      estimator: "Jordan Hale",
      ownerStaffId: "staff_jordan",
      winProbability: 70,
      nextStep: "Send staffing plan and 14-week look-ahead. Helen wants to start Labor Day.",
      createdAt: "2026-07-30T19:00:00.000Z",
    },
    {
      id: "opp_mob",
      name: "Cherry Creek Medical Office Building",
      clientId: "cli_meridian",
      primaryContactId: "con_meridian_ava",
      stage: "awarded",
      value: 31200000,
      bidDueAt: "2026-04-15",
      preBidWalkAt: "2026-03-20",
      location: "Cherry Creek, Denver, CO",
      projectType: "healthcare",
      deliveryMethod: "cm_at_risk",
      estimator: "Maya Chen",
      ownerStaffId: "staff_maya",
      winProbability: 100,
      nextStep: "Job is in the field — Elena has weekly OAC.",
      createdAt: "2026-01-08T15:00:00.000Z",
    },
    {
      id: "opp_rec",
      name: "Aurora Recreation Center Expansion",
      clientId: "cli_aurora",
      primaryContactId: "con_aurora_kim",
      stage: "awarded",
      value: 19800000,
      bidDueAt: "2026-05-20",
      preBidWalkAt: "2026-05-02",
      location: "Aurora, CO",
      projectType: "civic",
      deliveryMethod: "cm_at_risk",
      estimator: "Priya Shah",
      ownerStaffId: "staff_priya",
      winProbability: 100,
      nextStep: "Precon buyout of aquatics package.",
      createdAt: "2026-03-02T16:00:00.000Z",
    },
    {
      id: "opp_library",
      name: "Boulder Branch Library Renovation",
      clientId: "cli_hale",
      primaryContactId: "con_hale_sam",
      stage: "lost",
      value: 8400000,
      bidDueAt: "2026-07-10",
      preBidWalkAt: "2026-06-18",
      location: "Boulder, CO",
      projectType: "civic",
      deliveryMethod: "design_bid_build",
      estimator: "Maya Chen",
      ownerStaffId: "staff_maya",
      winProbability: 0,
      nextStep: "Lost on price. Debrief with Sam for the next civic bid.",
      lostReason: "Second low. $410K over apparent low bidder.",
      createdAt: "2026-05-14T14:00:00.000Z",
    },
  ],
  jobs: [
    {
      id: "job_mob",
      opportunityId: "opp_mob",
      name: "Cherry Creek Medical Office Building",
      clientId: "cli_meridian",
      status: "in_progress",
      contractValue: 31200000,
      startDate: "2026-06-02",
      substantialCompletion: "2027-08-15",
      superintendent: "Tom Brennan",
      projectManager: "Elena Voss",
      location: "Cherry Creek, Denver, CO",
      ownerStaffId: "staff_elena",
    },
    {
      id: "job_rec",
      opportunityId: "opp_rec",
      name: "Aurora Recreation Center Expansion",
      clientId: "cli_aurora",
      status: "precon",
      contractValue: 19800000,
      startDate: "2026-09-08",
      substantialCompletion: "2028-01-20",
      superintendent: "Tom Brennan",
      projectManager: "Luis Ortega",
      location: "Aurora, CO",
      ownerStaffId: "staff_luis",
    },
    {
      id: "job_mixed",
      opportunityId: null,
      name: "Wynkoop Mixed-Use",
      clientId: "cli_meridian",
      status: "punch",
      contractValue: 27400000,
      startDate: "2024-11-04",
      substantialCompletion: "2026-08-28",
      superintendent: "Tom Brennan",
      projectManager: "Elena Voss",
      location: "LoDo, Denver, CO",
      ownerStaffId: "staff_elena",
    },
    {
      id: "job_parking",
      opportunityId: null,
      name: "St. Luke's Staff Parking Structure",
      clientId: "cli_luke",
      status: "complete",
      contractValue: 14600000,
      startDate: "2024-03-11",
      substantialCompletion: "2026-02-20",
      superintendent: "Tom Brennan",
      projectManager: "Luis Ortega",
      location: "Highlands, Denver, CO",
      ownerStaffId: "staff_luis",
    },
    {
      id: "job_school",
      opportunityId: null,
      name: "DPS West High CTE Shop",
      clientId: "cli_dps",
      status: "in_progress",
      contractValue: 9200000,
      startDate: "2026-01-06",
      substantialCompletion: "2026-12-18",
      superintendent: "Tom Brennan",
      projectManager: "Luis Ortega",
      location: "West Colfax, Denver, CO",
      ownerStaffId: "staff_luis",
    },
  ],
  activities: [
    {
      id: "act_1",
      entityType: "opportunity",
      entityId: "opp_rino",
      type: "meeting",
      body: "Interview with Jon Park. They liked our schedule story. Asked for VE on podium vs. wood over podium by Thursday.",
      createdAt: "2026-08-18T16:30:00.000Z",
      author: "Jordan Hale",
    },
    {
      id: "act_2",
      entityType: "opportunity",
      entityId: "opp_imaging",
      type: "email",
      body: "Submitted GMP proposal and qualifications package. Bonding letter attached. Maya sent the bid recap internally.",
      createdAt: "2026-08-18T21:10:00.000Z",
      author: "Maya Chen",
    },
    {
      id: "act_3",
      entityType: "opportunity",
      entityId: "opp_cold",
      type: "call",
      body: "Wes confirmed the expansion is funded. Wants a design-build team on site Wednesday for a freezer layout walk.",
      createdAt: "2026-08-17T18:05:00.000Z",
      author: "Jordan Hale",
    },
    {
      id: "act_4",
      entityType: "job",
      entityId: "job_mob",
      type: "note",
      body: "Steel mill certs delayed a week. Elena is holding the sequence with a two-day float. Owner is aware.",
      createdAt: "2026-08-16T15:40:00.000Z",
      author: "Elena Voss",
    },
    {
      id: "act_5",
      entityType: "opportunity",
      entityId: "opp_montbello",
      type: "site_walk",
      body: "Mandatory pre-bid walk next week. Occupied campus — estimate needs a summer-only structural window.",
      createdAt: "2026-08-15T14:20:00.000Z",
      author: "Maya Chen",
    },
    {
      id: "act_6",
      entityType: "client",
      entityId: "cli_luke",
      type: "meeting",
      body: "Quarterly facilities check-in. Renee said imaging pavilion is the priority; another outpatient TI likely in Q1.",
      createdAt: "2026-08-12T17:00:00.000Z",
      author: "Jordan Hale",
    },
    {
      id: "act_7",
      entityType: "opportunity",
      entityId: "opp_library",
      type: "stage_change",
      body: "Moved to Lost. Second low by $410K. Sam offered a debrief after council award.",
      createdAt: "2026-07-18T19:00:00.000Z",
      author: "Maya Chen",
    },
    {
      id: "act_8",
      entityType: "job",
      entityId: "job_mixed",
      type: "note",
      body: "Punch list at 38 items. Elevator inspector scheduled Friday. Ava wants TCO before Labor Day weekend.",
      createdAt: "2026-08-14T13:15:00.000Z",
      author: "Elena Voss",
    },
    {
      id: "act_9",
      entityType: "opportunity",
      entityId: "opp_cherry_ti",
      type: "call",
      body: "Helen asked us to hold a crew for a Labor Day start. She is not shopping this one hard.",
      createdAt: "2026-08-19T14:50:00.000Z",
      author: "Jordan Hale",
    },
    {
      id: "act_10",
      entityType: "job",
      entityId: "job_rec",
      type: "meeting",
      body: "Precon kickoff with the city. Aquatics consultant still at 60% CDs. Buyout gated on that package.",
      createdAt: "2026-08-13T16:00:00.000Z",
      author: "Luis Ortega",
    },
  ],
  tasks: [
    {
      id: "tsk_1",
      title: "VE workshop for River North Apartments",
      dueAt: "2026-08-21",
      completed: false,
      relatedType: "opportunity",
      relatedId: "opp_rino",
      assignee: "Priya Shah",
    },
    {
      id: "tsk_2",
      title: "Follow up with Renee on imaging pavilion GMP",
      dueAt: "2026-08-22",
      completed: false,
      relatedType: "opportunity",
      relatedId: "opp_imaging",
      assignee: "Jordan Hale",
    },
    {
      id: "tsk_3",
      title: "Pre-bid walk — Front Range Cold Storage",
      dueAt: "2026-08-20",
      completed: false,
      relatedType: "opportunity",
      relatedId: "opp_cold",
      assignee: "Maya Chen",
    },
    {
      id: "tsk_4",
      title: "Send Cherry Creek TI staffing plan",
      dueAt: "2026-08-20",
      completed: false,
      relatedType: "opportunity",
      relatedId: "opp_cherry_ti",
      assignee: "Jordan Hale",
    },
    {
      id: "tsk_5",
      title: "Finish Montbello civil takeoff",
      dueAt: "2026-08-26",
      completed: false,
      relatedType: "opportunity",
      relatedId: "opp_montbello",
      assignee: "Maya Chen",
    },
    {
      id: "tsk_6",
      title: "Wynkoop punch — elevator inspection",
      dueAt: "2026-08-22",
      completed: false,
      relatedType: "job",
      relatedId: "job_mixed",
      assignee: "Elena Voss",
    },
    {
      id: "tsk_7",
      title: "Library bid debrief with Sam Moss",
      dueAt: "2026-08-27",
      completed: false,
      relatedType: "opportunity",
      relatedId: "opp_library",
      assignee: "Jordan Hale",
    },
    {
      id: "tsk_8",
      title: "Issue parking structure closeout binder",
      dueAt: "2026-08-12",
      completed: true,
      relatedType: "job",
      relatedId: "job_parking",
      assignee: "Luis Ortega",
    },
  ],
  catalog: demoOps.catalog,
  estimates: demoOps.estimates,
  estimateLines: demoOps.estimateLines,
  invoices: demoOps.invoices,
  invoiceLines: demoOps.invoiceLines,
  payments: demoOps.payments,
  events: demoOps.events,
  photos: demoOps.photos,
};
