import type { MarketingDrip, MarketingTemplate } from "@/lib/marketing/types";

export const MARKETING_TEMPLATES: MarketingTemplate[] = [
  {
    id: "tpl-storm-flyer",
    kind: "flyer",
    name: "Storm damage flyer",
    summary: "Neighborhood leave-behind after hail or wind. Merge the street and your card.",
    channel: "print",
    audience: "neighborhood",
    headline: "Hail hit {{jobCity}} — we’re already on your block",
    subhead: "Free roof inspections · Insurance claim help · Local crew",
    body: "{{companyName}} is working homes near {{jobAddress}}. Text or scan for a same-week inspection with {{staffName}}.",
    cta: "Book a free inspection",
    badge: "Storm response",
    accent: "#b45309",
    printReady: true,
    featured: true,
  },
  {
    id: "tpl-before-after-square",
    kind: "social_square",
    name: "Before / after square",
    summary: "Instagram and Facebook post from a finished job’s photos.",
    channel: "social",
    audience: "homeowner",
    headline: "Another roof done right in {{jobCity}}",
    subhead: "{{jobScope}}",
    body: "Project {{jobCode}} · Finished by {{staffName}} at {{companyName}}.",
    cta: "See our work",
    badge: "Just finished",
    accent: "#9a3412",
    printReady: false,
    featured: true,
  },
  {
    id: "tpl-story-promo",
    kind: "social_story",
    name: "Story promo",
    summary: "Vertical story with QR to your digital card.",
    channel: "social",
    audience: "homeowner",
    headline: "Need a roofer you can trust?",
    subhead: "{{staffName}} · {{staffTitle}}",
    body: "Scan for my card, reviews, and a quick text line.",
    cta: "Save my card",
    badge: "Tap to save",
    accent: "#c2410c",
    printReady: false,
    featured: false,
  },
  {
    id: "tpl-door-hanger",
    kind: "door_hanger",
    name: "Door hanger",
    summary: "Print-ready hanger for the street you’re already working.",
    channel: "print",
    audience: "neighborhood",
    headline: "We’re roofing your neighbor",
    subhead: "{{jobAddress}}",
    body: "Ask about our neighborhood rate while the crew is close. {{companyPhone}}",
    cta: "Call {{staffName}}",
    badge: "Neighbors",
    accent: "#7c2d12",
    printReady: true,
    featured: true,
  },
  {
    id: "tpl-yard-sign",
    kind: "yard_sign",
    name: "Yard sign",
    summary: "Simple job-site sign with phone and QR.",
    channel: "print",
    audience: "neighborhood",
    headline: "{{companyName}}",
    subhead: "Roofing · Restoration · Insurance work",
    body: "{{companyPhone}}",
    cta: "Scan for reviews",
    badge: "On site",
    accent: "#9a3412",
    printReady: true,
    featured: false,
  },
  {
    id: "tpl-postcard",
    kind: "postcard",
    name: "Thank-you postcard",
    summary: "Mailer after completion — review ask on the back.",
    channel: "print",
    audience: "homeowner",
    headline: "Thank you, {{contactName}}",
    subhead: "Your {{jobScope}} at {{jobAddress}} is complete.",
    body: "If we earned it, a Google review helps neighbors find a crew that shows up. — {{staffName}}",
    cta: "Leave a review",
    badge: "Thank you",
    accent: "#b45309",
    printReady: true,
    featured: false,
  },
  {
    id: "tpl-realtor-cobrand",
    kind: "realtor_cobrand",
    name: "Realtor co-brand kit",
    summary: "Preferred-vendor one-pager with partner name and listing address.",
    channel: "partner",
    audience: "realtor",
    headline: "{{partnerName}} × {{companyName}}",
    subhead: "Preferred roofing partner for listings that need a clean close",
    body: "Inspections, claim support, and schedule updates your sellers can trust. Listing: {{jobAddress}}.",
    cta: "Open partner portal",
    badge: "Partner",
    accent: "#0f766e",
    printReady: true,
    featured: true,
  },
  {
    id: "tpl-review-ask",
    kind: "review_ask",
    name: "Review ask card",
    summary: "QR to Google reviews plus a short SMS script.",
    channel: "print",
    audience: "homeowner",
    headline: "How did we do?",
    subhead: "30 seconds helps the next homeowner",
    body: "Thanks for trusting {{companyName}} on {{jobAddress}}. Tap below or scan to leave a Google review for {{staffName}}.",
    cta: "Leave a Google review",
    badge: "Reviews",
    accent: "#b45309",
    printReady: true,
    featured: true,
  },
  {
    id: "tpl-referral-ask",
    kind: "referral_ask",
    name: "Referral ask",
    summary: "Homeowner share graphic for the client portal referral flow.",
    channel: "web",
    audience: "homeowner",
    headline: "Know a neighbor who needs a roof?",
    subhead: "Send them our way — we’ll take care of them",
    body: "{{contactName}}, thanks again for {{jobScope}}. Share your portal link and we’ll treat your referral like family.",
    cta: "Send a referral",
    badge: "Referrals",
    accent: "#9a3412",
    printReady: false,
    featured: false,
  },
  {
    id: "tpl-case-study",
    kind: "case_study",
    name: "Job case study",
    summary: "One-page story from job photos, scope, and address.",
    channel: "print",
    audience: "homeowner",
    headline: "{{jobScope}} in {{jobCity}}",
    subhead: "{{jobCode}} · {{jobAddress}}",
    body: "{{companyName}} delivered a clean, on-schedule {{jobScope}} for {{contactName}}. Crew lead: {{staffName}}.",
    cta: "Start your project",
    badge: "Case study",
    accent: "#7c2d12",
    printReady: true,
    featured: true,
  },
  {
    id: "tpl-warranty-leavebehind",
    kind: "leave_behind",
    name: "Warranty leave-behind",
    summary: "Manufacturer / warranty one-pager from the company file directory.",
    channel: "print",
    audience: "homeowner",
    headline: "What’s covering this roof",
    subhead: "{{companyName}} workmanship + manufacturer warranty",
    body: "Ask {{staffName}} for the warranty packet on {{jobCode}}. License {{companyLicense}}.",
    cta: "Request warranty docs",
    badge: "Warranty",
    accent: "#9a3412",
    printReady: true,
    featured: false,
  },
  {
    id: "tpl-financing-leavebehind",
    kind: "leave_behind",
    name: "Financing leave-behind",
    summary: "Simple financing talk track for estimates.",
    channel: "print",
    audience: "homeowner",
    headline: "Pay over time, start this month",
    subhead: "Flexible options on approved credit",
    body: "{{staffName}} can walk {{contactName}} through monthly options for {{jobScope}} at {{jobAddress}}.",
    cta: "Ask about financing",
    badge: "Financing",
    accent: "#b45309",
    printReady: true,
    featured: false,
  },
];

export const MARKETING_DRIP_SEEDS: MarketingDrip[] = [
  {
    id: "drip-realtor-intro",
    name: "Realtor intro",
    channel: "email",
    audience: "realtor",
    subject: "Preferred roofing partner for your listings",
    body: "Hi {{partnerName}},\n\nI'm {{staffName}} with {{companyName}}. We help your sellers close with clean inspections, claim support, and schedule updates you can forward.\n\nWorth a 10-minute coffee this week?\n\n{{staffPhone}} · {{staffCardUrl}}",
    createdAt: "2026-09-01T12:00:00.000Z",
  },
  {
    id: "drip-realtor-followup",
    name: "Realtor follow-up",
    channel: "sms",
    audience: "realtor",
    subject: "",
    body: "Hi {{partnerName}} — {{staffName}} at {{companyName}}. Still glad to be a preferred roofer for your listings. Card: {{staffCardUrl}}",
    createdAt: "2026-09-01T12:00:00.000Z",
  },
  {
    id: "drip-storm-checkin",
    name: "Storm check-in",
    channel: "sms",
    audience: "neighborhood",
    subject: "",
    body: "Hi, this is {{staffName}} with {{companyName}}. Hail came through {{jobCity}} — happy to do a free roof check. Text {{staffPhone}} or reply here.",
    createdAt: "2026-09-01T12:00:00.000Z",
  },
  {
    id: "drip-review-ask",
    name: "Review ask",
    channel: "sms",
    audience: "homeowner",
    subject: "",
    body: "Hi {{contactName}}, {{staffName}} with {{companyName}}. If we earned it, a quick Google review helps neighbors find us: {{reviewUrl}}",
    createdAt: "2026-09-01T12:00:00.000Z",
  },
  {
    id: "drip-referral-ask",
    name: "Referral ask",
    channel: "email",
    audience: "homeowner",
    subject: "Know someone who needs a roofer?",
    body: "Hi {{contactName}},\n\nThanks again for trusting us on {{jobAddress}}. If a neighbor needs a roof, send them my way — I'll take care of them.\n\n{{staffName}}\n{{staffPhone}}\n{{portalHint}}",
    createdAt: "2026-09-01T12:00:00.000Z",
  },
];

export function marketingTemplateById(id: string) {
  return MARKETING_TEMPLATES.find((template) => template.id === id);
}
